import { Link } from "react-router-dom";

export default function StreakLeaderboardPreview({ snapshot, ownerName = "This student", loading = false }) {
  if (loading) return <section className="animate-pulse rounded-2xl border border-slate-200 bg-white p-6"><div className="h-5 w-48 rounded bg-slate-200"/><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{[1, 2, 3, 4].map((item) => <div key={item} className="aspect-square rounded-xl bg-slate-100"/>)}</div></section>;
  if (!snapshot || snapshot.visible === false) return null;
  const owner = snapshot.profileOwner;
  return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm md:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-extrabold uppercase tracking-widest text-orange-600">Top Streak Maintainers</p><h2 className="mt-2 text-2xl font-black text-slate-950">Consistency compounds.</h2></div><Link to="/leaderboard?type=streak" className="text-sm font-extrabold text-orange-700 hover:text-orange-600">View full streak leaderboard →</Link></div>
    {owner ? <div className="mt-5 grid gap-3 sm:grid-cols-3"><RankStat label="College rank" value={snapshot.collegeRank ? `#${snapshot.collegeRank}` : "Not ranked"}/><RankStat label="Global rank" value={snapshot.globalRank ? `#${snapshot.globalRank}` : "Not ranked"}/><RankStat label="Current streak" value={`${owner.streak.current} days`}/></div> : <p className="mt-5 rounded-lg bg-slate-50 p-4 text-sm font-semibold text-slate-600">{ownerName}'s rank appears after verified activity is synced.</p>}
    {snapshot.users?.length > 0 && <div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{snapshot.users.slice(0, 6).map((user) => <Link key={user.userId} to={`/profile/${user.userId}`} className="flex aspect-square min-w-0 flex-col items-center justify-between rounded-xl border border-slate-200 bg-slate-50 p-3 text-center transition duration-200 hover:-translate-y-0.5 hover:border-orange-300"><span className="self-end text-xs font-black text-orange-700">#{user.rank}</span><div className="grid h-12 w-12 place-items-center overflow-hidden rounded-full border-2 border-orange-400 bg-orange-500 font-black text-white">{user.avatar ? <img src={user.avatar} alt="" className="h-full w-full object-cover"/> : user.name.slice(0, 1)}</div><div className="w-full min-w-0"><p className="truncate text-sm font-extrabold text-slate-950">{user.name}</p><p className="mt-1 truncate text-[11px] text-slate-500">{user.college.name || "College not listed"}</p></div><p className="text-xs font-black text-orange-700">{user.streak.current} days</p></Link>)}</div>}
  </section>;
}

function RankStat({ label, value }) { return <div className="rounded-xl border border-orange-200 bg-orange-50 p-4"><p className="text-[11px] font-extrabold uppercase tracking-widest text-orange-800">{label}</p><p className="mt-2 text-2xl font-black text-slate-950">{value}</p></div>; }

