import { Link } from "react-router-dom";

const statusTone = { Ready: "bg-emerald-100 text-emerald-800", "Needs Improvement": "bg-amber-100 text-amber-900", Missing: "bg-red-100 text-red-800", Optional: "bg-slate-100 text-slate-700" };

export default function PlanDashboard({ plan, busyTask, recalculating, aiExplanation, aiLoading, aiError, onExplainPlan, onTaskToggle, onChangeGoal, onRecalculate }) {
  const activeTasks = plan.tasks.filter((task) => !task.archived);
  const weekTasks = activeTasks.filter((task) => task.scheduledWeek === plan.currentWeek);
  const fallbackTasks = activeTasks.filter((task) => !task.completed).slice(0, 5);
  const shownWeekTasks = weekTasks.length ? weekTasks : fallbackTasks;
  const today = new Date().toISOString().slice(0, 10);
  const todayTasks = activeTasks.filter((task) => task.scheduledDate && new Date(task.scheduledDate).toISOString().slice(0, 10) === today);
  const shownTodayTasks = todayTasks.length ? todayTasks : shownWeekTasks.filter((task) => !task.completed).slice(0, 4);
  const deadline = plan.target.deadline ? new Date(plan.target.deadline).toLocaleDateString(undefined, { month: "long", year: "numeric" }) : "Flexible";

  return <main className="min-h-screen bg-[#0f172a] px-5 py-10 text-white md:py-14"><div className="mx-auto max-w-6xl space-y-7">
    {plan.recalculated && <p className="rounded-lg border border-emerald-400/30 bg-emerald-400/10 px-4 py-3 text-sm font-semibold text-emerald-200">Your plan was recalculated from meaningful profile or verified-activity changes. Completed work was preserved.</p>}
    <header className="overflow-hidden rounded-2xl border border-white/10 bg-[#172033]"><div className="grid gap-7 p-6 md:grid-cols-[1.3fr_.7fr] md:p-9"><div><p className="text-xs font-extrabold uppercase tracking-[.22em] text-orange-400">Build my plan</p><p className="mt-5 text-sm font-extrabold uppercase tracking-wider text-slate-400">{plan.target.company || plan.target.type.replaceAll("-", " ")}</p><h1 className="mt-2 text-3xl font-black md:text-5xl">{plan.target.role}</h1><div className="mt-6 flex flex-wrap gap-x-7 gap-y-3 text-sm text-slate-300"><span><strong className="text-white">Target:</strong> {deadline}</span><span><strong className="text-white">Available:</strong> {plan.target.weeklyHours} hours/week</span><span><strong className="text-white">Estimate:</strong> {plan.timeline.minWeeks}–{plan.timeline.maxWeeks} weeks</span></div><p className="mt-4 text-xs leading-5 text-slate-400">{plan.timeline.disclaimer}</p></div><div className="rounded-2xl border border-orange-400/25 bg-orange-400/10 p-6"><p className="text-xs font-extrabold uppercase tracking-widest text-orange-300">Current readiness</p><p className="mt-3 text-6xl font-black text-white">{plan.readiness.total}%</p><p className="mt-3 text-xs leading-5 text-slate-300">Based on current skills and available verified benchmark data—not task checkboxes.</p></div></div><div className="flex flex-wrap items-center justify-between gap-3 border-t border-white/10 bg-black/10 px-6 py-4 md:px-9"><p className="text-sm font-semibold text-slate-300">Measure → Compare → Plan → Act → Track</p><div className="flex gap-2"><button onClick={onRecalculate} disabled={recalculating} className="rounded-lg border border-white/15 px-3 py-2 text-xs font-extrabold text-slate-200 disabled:opacity-50">{recalculating ? "Recalculating…" : "Recalculate"}</button><button onClick={onChangeGoal} className="rounded-lg bg-orange-500 px-3 py-2 text-xs font-extrabold text-slate-950">Change goal</button></div></div></header>

    <AIInsight explanation={aiExplanation} loading={aiLoading} error={aiError} onExplain={onExplainPlan}/>
    <PlanIntelligence plan={plan}/>
    <section className="grid gap-6 lg:grid-cols-[.85fr_1.15fr]"><SeniorMatch match={plan.seniorMatch}/><ReadinessBreakdown readiness={plan.readiness} profileSnapshot={plan.profileSnapshot}/></section>
    <GapAnalysis gaps={plan.gaps}/>
    <Timeline phases={plan.phases} currentPhase={plan.currentPhase}/>
    <section className="grid gap-6 lg:grid-cols-2"><TaskSection eyebrow={`Week ${plan.currentWeek}`} title="This week's priorities" tasks={shownWeekTasks} busyTask={busyTask} onToggle={onTaskToggle}/><TaskSection eyebrow="Today" title="Today's tasks" tasks={shownTodayTasks} busyTask={busyTask} onToggle={onTaskToggle}/></section>
    <Progress plan={plan}/>
  </div></main>;
}

function PlanIntelligence({ plan }) {
  const stage = plan.understoodCurrentStage;
  const guidance = plan.aiGuidance;
  if (!stage && !guidance) return null;
  const stageItems = [["Completed", stage?.completed, "text-emerald-300"], ["In progress", stage?.inProgress, "text-orange-300"], ["Needs attention", stage?.weakAreas, "text-amber-300"], ["Not started", stage?.notStarted, "text-slate-300"]].filter(([, items]) => items?.length);
  return <section className="grid gap-6 lg:grid-cols-2"><article className="rounded-2xl border border-white/10 bg-[#172033] p-6"><p className="text-xs font-extrabold uppercase tracking-widest text-orange-400">Your starting point</p><h2 className="mt-2 text-2xl font-black">What Newbert understood</h2><div className="mt-5 space-y-4">{stageItems.length ? stageItems.map(([label, items, tone]) => <div key={label}><p className="text-[11px] font-extrabold uppercase tracking-wider text-slate-500">{label}</p><div className="mt-2 flex flex-wrap gap-2">{items.map((item) => <span key={item} className={`rounded-md border border-white/10 px-2.5 py-1 text-xs font-bold ${tone}`}>{item}</span>)}</div></div>) : <p className="text-sm leading-6 text-slate-300">This plan is using your saved profile and selected goal. Add your current stage when changing the plan for more precise guidance.</p>}</div></article><article className="rounded-2xl border border-orange-400/20 bg-orange-400/10 p-6"><p className="text-xs font-extrabold uppercase tracking-widest text-orange-300">Your next 7 days</p><h2 className="mt-2 text-2xl font-black">Start with momentum</h2><div className="mt-5 space-y-3">{guidance?.nextSevenDays?.length ? guidance.nextSevenDays.map((item) => <div key={item.day} className="flex gap-3 border-b border-white/10 pb-3 last:border-0"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-orange-400 text-xs font-black text-slate-950">{item.day}</span><div><p className="text-sm font-extrabold">{item.title}</p><p className="mt-1 text-xs leading-5 text-slate-300">{item.detail}</p></div></div>) : <p className="text-sm text-slate-300">Your first tasks will appear here after plan generation.</p>}</div></article><article className="rounded-2xl border border-white/10 bg-[#172033] p-6 lg:col-span-2"><p className="text-xs font-extrabold uppercase tracking-widest text-orange-400">Why these priorities</p><div className="mt-4 grid gap-4 md:grid-cols-3">{guidance?.topPriorities?.map((priority) => <div key={priority.title} className="rounded-lg border border-white/10 bg-black/10 p-4"><p className="font-extrabold">{priority.title}</p><p className="mt-2 text-xs leading-5 text-slate-300">{priority.why}</p></div>)}</div>{guidance?.whatToAvoid?.length ? <div className="mt-5 border-t border-white/10 pt-4"><p className="text-[11px] font-extrabold uppercase tracking-wider text-orange-300">Things you should not focus on right now</p><ul className="mt-2 space-y-1 text-sm leading-6 text-slate-300">{guidance.whatToAvoid.map((item) => <li key={item}>• {item}</li>)}</ul></div> : null}</article></section>;
}

function AIInsight({ explanation, loading, error, onExplain }) {
  return <section className="rounded-2xl border border-violet-400/25 bg-gradient-to-br from-violet-400/10 to-[#172033] p-6 md:p-8"><div className="flex flex-wrap items-start justify-between gap-5"><div className="max-w-2xl"><p className="text-xs font-extrabold uppercase tracking-widest text-violet-300">Newbert AI insight</p><h2 className="mt-2 text-2xl font-black">Understand your plan</h2><p className="mt-2 text-sm leading-6 text-slate-300">Gemini explains your saved plan and deterministic readiness signals. It does not calculate or replace your scores.</p></div><button type="button" onClick={onExplain} disabled={loading} className="rounded-lg bg-violet-300 px-4 py-2.5 text-sm font-extrabold text-slate-950 transition hover:bg-violet-200 disabled:cursor-not-allowed disabled:opacity-60">{loading ? "Newbert AI is analyzing your plan…" : explanation ? "Refresh explanation" : "✨ Explain My Plan"}</button></div>{error && <p className="mt-5 rounded-lg border border-red-300/30 bg-red-400/10 px-4 py-3 text-sm font-semibold text-red-200">{error} Your roadmap and readiness data are still available.</p>}{explanation && <div className="mt-6 whitespace-pre-wrap rounded-xl border border-white/10 bg-black/15 p-5 text-sm leading-7 text-slate-200">{explanation}</div>}</section>;
}

function SeniorMatch({ match }) {
  if (!match) return <section className="rounded-2xl border border-white/10 bg-[#172033] p-6"><p className="text-xs font-extrabold uppercase tracking-widest text-orange-400">Closest senior match</p><h2 className="mt-5 text-2xl font-black">No verified senior benchmark available yet.</h2><p className="mt-3 text-sm leading-6 text-slate-300">Your plan was generated from your target requirements and saved profile. Newbert did not invent a senior.</p><Link to="/alumni-wall" className="mt-7 inline-flex text-sm font-extrabold text-orange-400">Browse verified alumni →</Link></section>;
  return <section className="rounded-2xl border border-white/10 bg-[#172033] p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-extrabold uppercase tracking-widest text-orange-400">Closest senior match</p><h2 className="mt-4 text-2xl font-black">{match.senior.name}</h2><p className="mt-1 text-sm text-slate-300">{match.senior.company}{match.senior.package != null ? ` · ${match.senior.package} LPA` : ""}</p><p className="mt-1 text-xs font-semibold text-slate-400">Verified senior from {match.senior.college}</p></div><p className="text-4xl font-black text-orange-400">{match.score}%</p></div><SkillRows label="Matched" skills={match.matchedSkills} prefix="✓" tone="text-emerald-300"/><SkillRows label="To build" skills={match.missingSkills} prefix="+" tone="text-orange-300"/><Link to={`/alumni-wall/${match.senior.id}`} className="mt-7 inline-flex rounded-lg bg-orange-500 px-4 py-2.5 text-sm font-extrabold text-slate-950">View Senior Profile →</Link></section>;
}

function SkillRows({ label, skills, prefix, tone }) { return <div className="mt-5"><p className="text-[11px] font-extrabold uppercase tracking-wider text-slate-500">{label}</p><div className="mt-2 flex flex-wrap gap-2">{skills.length ? skills.slice(0, 7).map((skill) => <span key={skill} className={`rounded-md border border-white/10 px-2.5 py-1 text-xs font-bold ${tone}`}>{prefix} {skill}</span>) : <span className="text-xs text-slate-500">No comparable skills available</span>}</div></div>; }

function ReadinessBreakdown({ readiness, profileSnapshot }) { const missingConnection = !profileSnapshot.github || !profileSnapshot.leetcode; return <section className="rounded-2xl border border-white/10 bg-[#172033] p-6"><p className="text-xs font-extrabold uppercase tracking-widest text-orange-400">Readiness signals</p><div className="mt-5 grid gap-4 sm:grid-cols-2">{Object.entries(readiness.categories).map(([key, value]) => <div key={key}><div className="flex justify-between text-sm font-bold"><span className="capitalize text-slate-200">{key}</span><span className="text-orange-300">{value}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-white/10"><div style={{ width: `${value}%` }} className="h-full rounded-full bg-orange-400"/></div></div>)}</div><div className="mt-6 border-t border-white/10 pt-4 text-xs font-semibold text-slate-400"><p>GitHub: {profileSnapshot.github ? `@${profileSnapshot.github.username} · ${profileSnapshot.github.publicRepos} repos` : "Not connected (not penalized as an unavailable category)"}</p><p className="mt-1">LeetCode: {profileSnapshot.leetcode ? `@${profileSnapshot.leetcode.username} · ${profileSnapshot.leetcode.totalSolved} solved` : "Not connected; saved skills are used instead"}</p>{missingConnection && <p className="mt-3 text-orange-300">Optional: connect GitHub or LeetCode for more accurate verified insights.</p>}</div></section>; }

function GapAnalysis({ gaps }) { return <section className="rounded-2xl border border-slate-200 bg-[#f8fafc] p-6 text-slate-950 md:p-8"><p className="text-xs font-extrabold uppercase tracking-widest text-orange-600">Your gaps</p><h2 className="mt-2 text-2xl font-black">What moves readiness next</h2><div className="mt-6 grid gap-5 md:grid-cols-2">{gaps.map((gap) => <article key={gap.key} className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="font-extrabold">{gap.label}</h3><p className="mt-1 text-xs leading-5 text-slate-500">{gap.detail}</p></div><span className={`shrink-0 rounded-full px-2.5 py-1 text-[10px] font-extrabold ${statusTone[gap.status]}`}>{gap.status}</span></div><div className="mt-4 flex items-center gap-3"><div className="h-2 flex-1 overflow-hidden rounded-full bg-slate-100"><div style={{ width: `${gap.currentScore}%` }} className="h-full rounded-full bg-teal-600"/></div><span className="text-xs font-extrabold text-slate-600">{gap.currentScore}%</span></div></article>)}</div></section>; }

function Timeline({ phases, currentPhase }) { return <section className="rounded-2xl border border-white/10 bg-[#172033] p-6 md:p-8"><p className="text-xs font-extrabold uppercase tracking-widest text-orange-400">Personalized timeline</p><h2 className="mt-2 text-2xl font-black">Your phases</h2><div className="mt-7 grid gap-3 md:grid-cols-5">{phases.map((phase, index) => { const current = phase.id === currentPhase?.id; return <article key={phase.id} className={`relative rounded-xl border p-4 ${current ? "border-orange-400 bg-orange-400/10" : "border-white/10 bg-white/5"}`}><p className="text-xs font-black text-orange-300">{String(index + 1).padStart(2, "0")}</p><h3 className="mt-2 font-extrabold">{phase.title}</h3><p className="mt-1 text-xs text-slate-400">Weeks {phase.startWeek}–{phase.endWeek}</p>{current && <span className="mt-3 inline-flex rounded-full bg-orange-400 px-2 py-1 text-[10px] font-black text-slate-950">You are here</span>}<ul className="mt-4 space-y-1 text-xs leading-5 text-slate-300">{phase.goals.slice(0, 3).map((goal) => <li key={goal}>• {goal}</li>)}</ul></article>; })}</div></section>; }

function TaskSection({ eyebrow, title, tasks, busyTask, onToggle }) { const completed = tasks.filter((task) => task.completed).length; const percent = tasks.length ? Math.round((completed / tasks.length) * 100) : 0; return <section className="rounded-2xl border border-white/10 bg-[#172033] p-6"><div className="flex items-end justify-between gap-3"><div><p className="text-xs font-extrabold uppercase tracking-widest text-orange-400">{eyebrow}</p><h2 className="mt-2 text-xl font-black">{title}</h2></div><p className="text-xs font-extrabold text-slate-400">{completed} / {tasks.length} · {percent}%</p></div><div className="mt-5 divide-y divide-white/10">{tasks.length ? tasks.map((task) => <label key={task.id} className="flex cursor-pointer gap-3 py-4"><input type="checkbox" checked={task.completed} disabled={busyTask === task.id} onChange={() => onToggle(task)} className="mt-0.5 h-4 w-4 accent-orange-500"/><span><span className={`block text-sm font-bold ${task.completed ? "text-slate-500 line-through" : "text-slate-100"}`}>{task.title}</span>{task.description && <span className="mt-1 block text-xs leading-5 text-slate-400">{task.description}</span>}{task.verifiable && <span className="mt-1 block text-[10px] font-extrabold uppercase tracking-wider text-teal-300">Readiness changes only after profile evidence updates</span>}</span></label>) : <p className="py-5 text-sm text-slate-400">No tasks are scheduled here yet.</p>}</div></section>; }

function Progress({ plan }) { return <section className="rounded-2xl border border-orange-400/20 bg-orange-400/10 p-6 md:p-8"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-extrabold uppercase tracking-widest text-orange-300">Plan progress</p><h2 className="mt-2 text-3xl font-black">{plan.progress.completedTasks} / {plan.progress.totalTasks} tasks</h2><p className="mt-2 text-sm text-slate-300">{plan.progress.percent}% completed · Actual plan streak: {plan.progress.streak || 0} days</p></div><p className="max-w-md text-xs leading-5 text-slate-400">Task completion measures execution. Placement readiness remains based on profile, skills, projects, and verified external evidence.</p></div><div className="mt-5 h-3 overflow-hidden rounded-full bg-black/20"><div style={{ width: `${plan.progress.percent}%` }} className="h-full rounded-full bg-orange-400"/></div></section>; }
