// This configuration drives validation, branching, progress, review and the chat renderer.
const text = (id, label, required=false, extra={}) => ({id,label,type:'text',required,maxLength:120,...extra});
const long = (id,label,required=false) => text(id,label,required,{type:'textarea',maxLength:3000});
const num = (id,label,min=0,max=1000000,required=false) => ({id,label,type:'number',min,max,required});
const choice = (id,label,options,required=false) => ({id,label,type:'choice',options,required});
const list = (id,label,options=[]) => ({id,label,type:'multi-choice',options,custom:true});
const url = (id,label,required=false) => ({id,label,type:'url',required});
const yes = (id,label) => ({id,label,type:'yes-no'});
const date = (id,label) => ({id,label,type:'date'});
const q = (id,section,prompt,type,extra={}) => ({id,section,text:prompt,type,required:false,...extra});
const employment = {field:'careerPath',values:['PLACEMENT','OFF_CAMPUS','INTERNSHIP_PPO']};
const gate = {any:[{field:'careerPath',values:['GATE']},{field:'attemptedGate',values:[true]}]};
const CAREER_OPTIONS = [
  ['PLACEMENT','Campus placement'],['OFF_CAMPUS','Off-campus placement'],['INTERNSHIP_PPO','Internship → PPO'],['GATE','GATE'],['PSU','PSU'],['HIGHER_STUDIES','M.Tech / higher studies'],['MS_ABROAD','MS abroad'],['STARTUP','Startup / entrepreneurship'],['GOVERNMENT_EXAM','Government exam'],['OTHER','Other'],
].map(([value,label])=>({value,label}));
const PLATFORMS = ['GITHUB','LEETCODE','GEEKSFORGEEKS','CODECHEF','CODEFORCES','HACKERRANK','HACKEREARTH','CODE360','ATCODER','INTERVIEWBIT','KAGGLE','STACK_OVERFLOW','BEHANCE','DRIBBBLE','GITLAB','PORTFOLIO','OTHER'];
const TOPICS = ['Arrays','Strings','Hashing','Two Pointers','Sliding Window','Binary Search','Linked List','Stack','Queue','Monotonic Stack','Trees','BST','Heap / Priority Queue','Graphs','Greedy','Dynamic Programming','Trie','Backtracking','Bit Manipulation','Intervals','Math'];
const projectFields=[text('name','Project name',true),long('description','What problem did it solve?',true),list('techStack','Technologies'),url('githubUrl','GitHub link'),url('liveUrl','Live link'),choice('ownership','Individual or team?',['INDIVIDUAL','TEAM']),long('contribution','What did you personally contribute?'),text('duration','Approximate duration'),yes('onResume','Was it on your resume?'),yes('discussedInInterview','Did it come up in an interview?'),long('interviewQuestions','What were you asked?')];
const internshipFields=[text('company','Company',true),text('role','Role',true),choice('payment','Paid or unpaid?',['PAID','UNPAID']),num('stipend','Monthly stipend (INR)'),date('startDate','Start date'),date('endDate','End date (leave blank if ongoing)'),text('duration','Duration'),list('techStack','Technologies'),text('source','How did you find it?'),long('work','What did you work on?'),choice('mode','Working arrangement',['REMOTE','HYBRID','ONSITE']),yes('ppo','Did it lead to a PPO?'),long('usefulness','How did it help with selection?')];
const roundFields=[num('roundNumber','Round number',1,50,true),choice('type','Round type',['ONLINE_ASSESSMENT','TECHNICAL','HR','MANAGERIAL','GROUP_DISCUSSION','OTHER'],true),list('questions','Questions asked'),list('topics','Topics'),choice('difficulty','Difficulty',['EASY','MEDIUM','HARD']),long('description','What happened in this round?')];
const interviewFields=[text('company','Company',true),text('role','Role'),{id:'rounds',label:'Interview rounds',type:'collection',fields:roundFields,required:true},choice('overallDifficulty','Overall difficulty',['EASY','MEDIUM','HARD']),choice('result','Result',['SELECTED','REJECTED','WAITLIST','PENDING','WITHDREW'])];
const resourceFields=[text('name','Resource name',true),text('platform','Platform / teacher'),choice('kind','Resource type',['YOUTUBE','COURSE','BOOK','SHEET','TEST_SERIES','WEBSITE','TEACHER','COMMUNITY','OTHER']),choice('payment','Free or paid?',['FREE','PAID']),num('price','Approximate price (INR)'),url('url','Resource link'),text('topic','Topic'),num('rating','Your rating out of 5',1,5),yes('helpedSelection','Did it help with selection?'),yes('recommend','Would you recommend it?'),long('audience','Who would benefit most?'),long('disliked','What could have been better?')];
const questions=[
  q('name','Basics','What name should juniors know you by?','text',{required:true,maxLength:100}),
  q('college','Basics','Which college is your journey connected to?','college',{required:true}),
  q('branch','Basics','What was your branch?','text',{required:true,maxLength:80}),
  q('graduationYear','Basics','Which year did you graduate, or expect to graduate?','year',{required:true,min:1950,max:new Date().getFullYear()+8}),
  q('degree','Basics','What degree did you study?','text',{required:true,maxLength:100}),
  q('introduction','Basics','Want to add a photo, your city or a short introduction?','object',{fields:[url('avatarUrl','Profile image URL'),text('city','Current city'),{...long('bio','A short introduction'),maxLength:1200}]}),
  q('academics','Academics','Which academic details would you like to share?','object',{fields:[num('cgpa','CGPA (out of 10)',0,10),num('tenthPercentage','Class 10 percentage',0,100),num('twelfthPercentage','Class 12 percentage',0,100),yes('hadBacklogs','Any backlog during placement?'),num('activeBacklogs','Active backlogs at selection',0,100)]}),
  q('socialLinks','Profiles','Where can juniors find your professional work?','object',{fields:[url('linkedin','LinkedIn profile'),url('portfolio','Portfolio / personal website')]}),
  q('platforms','Profiles','Where did you practice or share your work? Choose only the platforms you used.','platform-selector',{options:PLATFORMS}),
  q('careerPath','Career','Which path did you take after college?','choice',{required:true,options:CAREER_OPTIONS}),
  q('placement','Career','Tell me about the offer you want to share with juniors.','object',{required:true,when:employment,ai:true,fields:[text('company','Company',true),text('role','Role',true),choice('companyType','Company type',['PRODUCT','SERVICE','STARTUP','CONSULTING','CORE','GOVERNMENT','OTHER']),num('ctc','Annual CTC (LPA)'),num('baseSalary','Annual base salary (LPA)'),num('stipend','Monthly internship stipend (INR)'),text('location','Location'),num('offerYear','Offer year',1950,new Date().getFullYear()+1),choice('placementType','How did the offer happen?',['ON_CAMPUS','OFF_CAMPUS','REFERRAL']),choice('offerType','Offer type',['INTERNSHIP','PPO','FULL_TIME']),num('applications','Approximate applications',0,100000),num('offers','Number of offers',0,1000)]}),
  q('careerOutcome','Career','What outcome or next step would you like to share?','object',{required:true,when:{field:'careerPath',values:['HIGHER_STUDIES','MS_ABROAD','STARTUP','GOVERNMENT_EXAM','OTHER']},fields:[text('title','Outcome / role / programme',true),text('organisation','Organisation or institution'),long('description','Tell juniors what happened',true)]}),
  q('attemptedGate','Career','Did you also attempt GATE?','yes-no',{when:{field:'careerPath',not:['GATE']}}),
  q('gateProfile','GATE','Let’s record your GATE attempt and outcome. Share only what you are comfortable sharing.','object',{required:true,when:gate,ai:true,fields:[text('paper','GATE paper',true),num('year','Exam year',1990,new Date().getFullYear()+1,true),num('attempt','Attempt number',1,50),num('marks','Marks',-34,100),num('score','Score',0,1000),num('air','All India Rank',1,10000000),long('outcome','Admission, qualification or final decision',true),text('institute','M.Tech institution'),text('specialization','Specialization'),text('psuOffers','PSU offers'),list('strongSubjects','Strong subjects'),list('weakSubjects','Weak subjects'),text('coaching','Coaching / course'),text('testSeries','Test series'),text('books','Books / resources')]}),
  q('psuProfile','GATE','Tell me about your PSU selection.','object',{required:true,when:{field:'careerPath',values:['PSU']},fields:[text('name','PSU name',true),text('role','Role',true),num('gateScore','GATE score used',0,1000),num('gateRank','GATE rank used',1,10000000),long('selectionProcess','Selection process'),long('interview','Interview experience'),num('ctc','Annual CTC (LPA)'),text('location','Location'),num('year','Year selected',1990,new Date().getFullYear()+1)]}),
  q('usedDsa','Preparation','Was coding or DSA part of your preparation?','yes-no'),
  q('dsaPreparation','Preparation','Around selection time, what did your DSA preparation look like? Current totals are separate.','object',{when:{field:'usedDsa',values:[true]},ai:true,fields:[text('primaryLanguage','Primary language'),num('solvedAtSelection','Problems solved at selection (approx.)'),yes('estimated','Is that count an estimate?'),num('currentSolved','Current solved count (optional)'),num('contestRating','Contest rating',0,10000),num('contestsParticipated','Contests participated',0,10000),list('strongTopics','Strong topics',TOPICS),list('weakTopics','Weak topics',TOPICS),text('revision','How did you revise?'),text('resource','Most useful sheet / resource')]}),
  q('skillsAtSelection','Preparation','What technical skills did you know THEN, when you were selected or reached your outcome?','skills',{required:true,ai:true,fields:[text('name','Skill',true),choice('category','Category',['LANGUAGE','FRONTEND','BACKEND','DATABASE','CLOUD','DEVOPS','AI_ML','MOBILE','CORE_CS','SYSTEM_DESIGN','TESTING','CORE_ENGINEERING','OTHER']),choice('level','Your level then',['BEGINNER','INTERMEDIATE','ADVANCED'])]}),
  q('preparation','Preparation','When did you start, and how much time did preparation take?','object',{required:true,fields:[choice('startedIn','When did you start?',['YEAR_1','YEAR_2','YEAR_3','FINAL_YEAR','AFTER_GRADUATION'],true),num('months','Approximate months',0,120,true),num('hoursPerDay','Average hours per day',0,24)]}),
  q('preparationJourney','Preparation','How did your preparation progress? A few phases can help juniors plan their own path.','timeline',{ai:true,fields:[text('title','Phase title',true),text('duration','Duration (for example, 2 months)'),long('description','What did you focus on?')]}),
  q('projects','Projects','Which projects mattered most on your resume or in interviews? Start with one; you can add more.','projects',{ai:true,fields:projectFields}),
  q('internships','Internships','Did any internships shape your journey?','internships',{ai:true,fields:internshipFields}),
  q('interviews','Interviews','What happened in your interviews? Add a company, then the rounds you remember.','interview-rounds',{ai:true,fields:interviewFields}),
  q('resources','Resources','Which resources were actually worth your time?','resource-list',{ai:true,fields:resourceFields}),
  q('advice','Advice','What is one piece of advice juniors from your college should hear?','textarea',{required:true,maxLength:3000}),
  q('adviceDetails','Advice','Want to leave a few more honest lessons from your journey?','object',{fields:[long('biggestMistake','Your biggest mistake'),long('startEarlier','What should juniors start earlier?'),long('overrated','What was overrated?'),long('underrated','What was underrated?'),long('wouldDoDifferently','What would you change if restarting in second year?'),long('whatWorked','What helped you most?'),long('finalMessage','One final message')]}),
  q('mentorInterest','Mentorship','Would you like to help juniors as a mentor?','choice',{options:['YES','LATER','NO']}),
  q('mentorship','Mentorship','How would you like to mentor? This does not set up payments.','object',{when:{field:'mentorInterest',values:['YES']},fields:[list('topics','Topics',['Placement','DSA','Web Development','AI/ML','GATE','Resume','Interview','Projects','Career guidance']),choice('method','Preferred method',['CHAT','AUDIO','VIDEO']),text('availability','Availability'),num('sessionMinutes','Session length in minutes',15,180),choice('payment','Free or paid?',['FREE','PAID']),num('price','Planned price (INR)'),num('maxSessionsPerWeek','Maximum sessions per week',0,30)]}),
  q('verificationSources','Verification','Would you like to submit evidence for review? Evidence stays private; adding a link never verifies an outcome automatically.','multi-choice',{options:['LINKEDIN','GITHUB','LEETCODE','COMPANY_EMAIL','OFFER_LETTER','EMPLOYEE_ID','GATE_SCORECARD','COLLEGE_RECORD','OTHER']}),
  q('privacy','Privacy','Choose who can see your story. You can review each field before publishing.','privacy',{required:true}),
];
const COLLECTION_TYPES=['skills','projects','internships','interview-rounds','timeline','resource-list','collection'];
module.exports={questions,PLATFORMS,CAREER_OPTIONS,COLLECTION_TYPES};
