const SKILL_SIGNALS = Object.freeze({
  react: { label: "React", category: "frameworks", dependencies: ["react", "react-dom"], extensions: [".jsx", ".tsx"], patterns: ["useState(", "useEffect(", "createContext(", "react-router"] },
  javascript: { label: "JavaScript", category: "languages", extensions: [".js", ".jsx", ".mjs"] },
  typescript: { label: "TypeScript", category: "languages", dependencies: ["typescript"], extensions: [".ts", ".tsx"] },
  nodejs: { label: "Node.js", category: "frameworks", dependencies: ["express", "fastify", "koa"], patterns: ["process.env", "require(", "node:"] },
  express: { label: "Express.js", category: "frameworks", dependencies: ["express"], patterns: ["express()", "express.Router("] },
  mongodb: { label: "MongoDB", category: "databases", dependencies: ["mongodb", "mongoose"], patterns: ["MongoClient", "mongoose.connect"] },
  mongoose: { label: "Mongoose", category: "databases", dependencies: ["mongoose"], patterns: ["new mongoose.Schema", "mongoose.model("] },
  restapis: { label: "REST APIs", category: "fundamentals", patterns: ["fetch(", "axios.", ".get(", ".post(", "router.get(", "router.post("] },
  tailwind: { label: "Tailwind CSS", category: "ui_tooling", dependencies: ["tailwindcss"], patterns: ["@tailwind", "className="] },
  zustand: { label: "Zustand", category: "frameworks", dependencies: ["zustand"], patterns: ["create((", "createStore("] },
  redux: { label: "Redux", category: "frameworks", dependencies: ["redux", "@reduxjs/toolkit"], patterns: ["createSlice(", "configureStore("] },
  nextjs: { label: "Next.js", category: "frameworks", dependencies: ["next"], patterns: ["next/navigation", "next/router"] },
  jwt: { label: "JWT", category: "fundamentals", dependencies: ["jsonwebtoken", "jose"], patterns: ["jwt.sign(", "jwt.verify("] },
  oauth: { label: "OAuth", category: "fundamentals", dependencies: ["passport", "@react-oauth/google"], patterns: ["OAuth2Client", "passport.authenticate"] },
  firebase: { label: "Firebase", category: "databases", dependencies: ["firebase", "firebase-admin"], patterns: ["initializeApp("] },
  sql: { label: "SQL", category: "languages", dependencies: ["pg", "mysql2", "sequelize", "prisma", "@prisma/client"], extensions: [".sql"] },
  postgresql: { label: "PostgreSQL", category: "databases", dependencies: ["pg", "pg-hstore", "prisma"], patterns: ["new Pool(", "new Client("] },
  mysql: { label: "MySQL", category: "databases", dependencies: ["mysql2", "mysql"], patterns: ["createConnection(", "createPool("] },
  redis: { label: "Redis", category: "databases", dependencies: ["redis", "ioredis"], patterns: ["createClient(", "new Redis("] },
  prisma: { label: "Prisma", category: "databases", dependencies: ["prisma", "@prisma/client"], patterns: ["new PrismaClient("] },
  docker: { label: "Docker", category: "tools", patterns: ["FROM ", "WORKDIR ", "RUN "] },
  cicd: { label: "CI/CD (GitHub Actions)", category: "tools", patterns: ["on: [push]", "jobs:"] },
  vite: { label: "Vite", category: "tools", dependencies: ["vite"], patterns: ["defineConfig("] },
  python: { label: "Python", category: "languages", extensions: [".py"] },
  flask: { label: "Flask", category: "frameworks", dependencies: ["flask"], patterns: ["Flask(__name__)"] },
  fastapi: { label: "FastAPI", category: "frameworks", dependencies: ["fastapi"], patterns: ["FastAPI("] },
  django: { label: "Django", category: "frameworks", dependencies: ["django"], patterns: ["django.db", "urlpatterns ="] },
  tensorflow: { label: "TensorFlow", category: "frameworks", dependencies: ["tensorflow"], patterns: ["import tensorflow"] },
  pytorch: { label: "PyTorch", category: "frameworks", dependencies: ["torch"], patterns: ["import torch"] },
  scikitlearn: { label: "scikit-learn", category: "frameworks", dependencies: ["scikit-learn", "sklearn"], patterns: ["from sklearn", "import sklearn"] },
});

const UTILITY_PACKAGES = new Set([
  "axios",
  "clsx",
  "lucide-react",
  "react-toastify",
  "date-fns",
  "dotenv",
  "cors",
  "cookie-parser",
  "nodemon",
  "bcrypt",
  "bcryptjs",
  "class-variance-authority",
  "tailwind-merge",
  "framer-motion",
  "morgan",
  "concurrently",
  "cross-env",
  "rimraf",
  "path",
  "fs",
  "body-parser",
]);

module.exports = { SKILL_SIGNALS, UTILITY_PACKAGES };
