const mongoose = require("mongoose");

const jobSchema = new mongoose.Schema({
  title: { type: String, required: true, trim: true, maxlength: 140 },
  company: { type: String, required: true, trim: true, maxlength: 120 },
  companySlug: { type: String, trim: true, maxlength: 140 },
  department: { type: String, trim: true, maxlength: 120 },
  roleCategory: { type: String, trim: true, maxlength: 80 },
  location: { type: mongoose.Schema.Types.Mixed, default: null },
  multipleLocations: { type: [mongoose.Schema.Types.Mixed], default: [] },
  workMode: { type: String, enum: ["onsite", "hybrid", "remote", "unknown"], default: "unknown" },
  employmentType: { type: String, enum: ["internship", "full-time", "part-time", "contract", "apprenticeship", "temporary", "unknown"], default: "unknown" },
  experienceLevel: { type: String, enum: ["intern", "entry-level", "junior", "mid", "senior", "unspecified"], default: "unspecified" },
  experience: { type: mongoose.Schema.Types.Mixed, default: null },
  salary: { type: mongoose.Schema.Types.Mixed, default: null },
  compensation: { type: mongoose.Schema.Types.Mixed, default: null },
  description: { type: String, required: true, trim: true, maxlength: 5000 },
  skills: { type: [String], default: [] },
  requirements: { type: mongoose.Schema.Types.Mixed, default: () => ({ requiredSkills: [], preferredSkills: [], csFundamentals: [], minimumCgpa: null, allowedBranches: [], graduationYears: [], experienceYears: null }) },
  responsibilities: { type: [String], default: [] },
  qualifications: { type: [String], default: [] },
  projectExpectations: { type: [String], default: [] },
  selectionProcess: { type: [String], default: [] },
  benefits: { type: [String], default: [] },
  companyDescription: { type: String, trim: true, maxlength: 3000 },
  applicationInstructions: { type: String, trim: true, maxlength: 3000 },
  application: { type: mongoose.Schema.Types.Mixed, default: null },
  applyUrl: { type: String, required: true, trim: true },
  source: { type: mongoose.Schema.Types.Mixed, default: null },
  verification: { type: mongoose.Schema.Types.Mixed, default: () => ({ status: "pending", sourceType: "unknown", verifiedAt: null, lastCheckedAt: null }) },
  deadline: Date,
  postedAt: Date,
  joiningDate: Date,
  internshipDuration: { type: mongoose.Schema.Types.Mixed, default: null },
  expiresAt: Date,
  jdAnalysis: { type: mongoose.Schema.Types.Mixed, default: null },
  active: { type: Boolean, default: true },
}, { timestamps: true });

jobSchema.index({ active: 1, createdAt: -1 });
module.exports = mongoose.model("Job", jobSchema);
