import { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import API from '../Services/api';
import useAuth from '../hook/useAuth';
import { academicBranches } from '../utils/academicYear';
import { academicCatalog } from '../data/academicStudy';
import { studyCourses } from '../data/studyCatalog';
import useStudyCatalog from '../hook/useStudyCatalog';
import LecturePlayer from '../components/LecturePlayer';
import '../study.css';
import '../study-content.css';
const emptyLesson={url:'',title:'',summary:'',minutes:0,mentorName:'',unit:1,order:0,published:false,resources:[],quiz:[],practice:[]};
export default function AdminStudy() {
  const {isAuthenticated}=useAuth();
  const content=useStudyCatalog();
  const [data,setData]=useState({subjects:[],lessons:[]}), [loading,setLoading]=useState(true), [error,setError]=useState(''), [message,setMessage]=useState(''), [busy,setBusy]=useState(false);
  const [branch,setBranch]=useState('electrical'), [year,setYear]=useState(1), [semester,setSemester]=useState(1), [scheme,setScheme]=useState(2022), [subjectId,setSubjectId]=useState('');
  const [form,setForm]=useState(emptyLesson), [preview,setPreview]=useState(null), [edit,setEdit]=useState(false), [newSubject,setNewSubject]=useState(false);
  const [subjectForm,setSubjectForm]=useState({title:'',code:'',id:'',units:Array(5).fill('')});
  const load=useCallback(async()=>{setLoading(true);setError('');try {const {data}=await API.get('/admin/study');setData(data);} catch(e) {setError(e.response?.data?.message || 'Content administration could not be loaded.');} finally {setLoading(false);}},[]);
  useEffect(()=>{if(isAuthenticated) void load(); else setLoading(false);},[isAuthenticated,load]);
  const subjects=[...new Map([...academicCatalog.subjects,...data.subjects].map(s=>[s.id,s])).values()].filter(s=>s.branches.includes(branch)&&s.year===Number(year)&&s.semesters.includes(Number(semester))&&(Number(year)!==1||s.scheme===Number(scheme)));
  const subject=subjects.find(s=>s.id===subjectId);
  const baseline=studyCourses.find(c=>c.id===subject?.lectureCollection)?.lessons || [];
  const lessons=subject?[...baseline.filter(l=>!l._id&&!data.lessons.some(d=>d.subjectId===subject.id&&d.videoId===l.videoId)).map(l=>({...l,published:true})),...data.lessons.filter(l=>l.subjectId===subject.id)].sort((a,b)=>(a.order||0)-(b.order||0)):[];
  const change=(field,value)=>{setForm(f=>({...f,[field]:value}));setMessage('');};
  const resetLesson=()=>{setForm(emptyLesson);setPreview(null);setEdit(false);};
  const importVideo=async()=>{setBusy(true);setError('');setPreview(null);try {const {data}=await API.post('/admin/study/import-video',{url:form.url});setForm(f=>({...f,...data.video}));setPreview(data.video);setMessage(data.video.notice || 'Video details imported. Review them before publishing.');} catch(e) {setError(e.response?.data?.message || 'Video details could not be fetched. Retry or save a draft manually.');} finally {setBusy(false);}};
  const save=async published=>{if(!subject) return;setBusy(true);setError('');setMessage('');try {await API.put('/admin/study/lessons',{...form,subjectId:subject.id,published,edit});await load();await content.refresh();setEdit(true);setForm(f=>({...f,published}));setMessage(published?'Lesson published in Study Studio.':'Draft saved. Hidden from students.');} catch(e) {setError(e.response?.data?.message || 'Lesson was not saved.');} finally {setBusy(false);}};
  const createSubject=async e=>{e.preventDefault();setBusy(true);setError('');try {const {data}=await API.post('/admin/study/subjects',{...subjectForm,branch,year:Number(year),semester:Number(semester),scheme:Number(scheme)});await load();setSubjectId(data.subject.id);setNewSubject(false);resetLesson();setMessage('Subject created. Add and publish a lesson to make it visible.');} catch(e) {setError(e.response?.data?.message || 'Subject was not created.');} finally {setBusy(false);}};
  const chooseLesson=l=>{setForm({...emptyLesson,...l,url:l.url || `https://www.youtube.com/watch?v=${l.videoId}`,resources:l.resources || [],quiz:l.quiz || [],practice:l.practice || []});setEdit(true);setPreview({videoId:l.videoId,thumbnail:`https://i.ytimg.com/vi/${l.videoId}/hqdefault.jpg`});setMessage('');};
  if(!isAuthenticated)return <main className="studio-page"><div className="study-admin"><h1>Study Studio administration</h1><p><Link to="/profile">Sign in with your administrator account</Link> to manage content.</p></div></main>;
  return <main className="studio-page"><div className="study-admin"><header><p className="studio-eyebrow">NEWBERT / CONTENT ADMINISTRATION</p><h1>Build the next lesson.</h1><p>Existing lectures and student notebooks stay connected. Drafts and empty subjects stay hidden from students.</p><div className="study-row"><Link to="/study">Open Study Studio</Link><Link to="/admin/study/doubts">Mentor doubt inbox →</Link><Link to="/admin/notes">Existing notes administration</Link></div></header>
    {error&&<div role="alert" className="studio-notice">{error}<button onClick={load} disabled={busy}>Retry access</button></div>}{message&&<p role="status" className="studio-notice">{message}</p>}
    {loading?<p role="status">Loading content…</p>:error&&!data.lessons.length&&!data.subjects.length?<p>Administrator access is checked by the server. Keep your account email in ADMIN_EMAILS.</p>:<>
    <section className="study-panel study-form"><h2>1. Choose the lesson’s home</h2><fieldset disabled={busy}><div className="study-admin-grid"><label>Branch<select value={branch} onChange={e=>{setBranch(e.target.value);setSubjectId('');resetLesson();}}>{academicBranches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Year<select value={year} onChange={e=>{const y=Number(e.target.value);setYear(y);setSemester(y*2-1);setSubjectId('');resetLesson();}}>{[1,2,3,4].map(y=><option key={y} value={y}>Year {y}</option>)}</select></label><label>Semester<select value={semester} onChange={e=>{setSemester(Number(e.target.value));setSubjectId('');resetLesson();}}>{[year*2-1,year*2].map(s=><option key={s} value={s}>Semester {s}</option>)}</select></label>{year===1&&<label>Curriculum<select value={scheme} onChange={e=>{setScheme(Number(e.target.value));setSubjectId('');resetLesson();}}><option value={2022}>2022 scheme</option><option value={2026}>2026 scheme</option></select></label>}</div><label>Subject<select value={subjectId} onChange={e=>{setSubjectId(e.target.value);resetLesson();setNewSubject(false);}}><option value="">Choose a subject</option>{subjects.map(s=><option key={s.id} value={s.id}>{s.code} · {s.title}</option>)}</select></label><button type="button" className="studio-secondary" onClick={()=>setNewSubject(v=>!v)}>{newSubject?'Cancel new subject':'Create a subject'}</button></fieldset></section>
    {newSubject&&<form onSubmit={createSubject} className="study-panel study-form"><h2>Create subject</h2><fieldset disabled={busy}>{[['title','Subject name'],['code','Course code'],['id','Unique identifier (lowercase letters, numbers and hyphens)']].map(([field,label])=><label key={field}>{label}<input required maxLength={field==='title'?200:field==='code'?40:60} pattern={field==='id'?'[a-z0-9-]+':undefined} value={subjectForm[field]} onChange={e=>setSubjectForm({...subjectForm,[field]:e.target.value})}/></label>)}{subjectForm.units.map((u,i)=><label key={i}>Unit {i+1} heading<input required maxLength={200} value={u} onChange={e=>setSubjectForm({...subjectForm,units:subjectForm.units.map((v,j)=>i===j?e.target.value:v)})}/></label>)}<button className="studio-primary">Create subject</button></fieldset></form>}
    {subject&&<><section className="study-panel"><h2>{subject.title}</h2><p>{lessons.filter(l=>l.published).length} published · {lessons.filter(l=>!l.published).length} drafts{!lessons.some(l=>l.published)&&' · Hidden from students'}</p><div className="study-admin-list">{lessons.map(l=><div className="study-row" key={l.videoId}><span>{l.title} · Unit {l.unit} · {l.published?'Published':'Draft'}</span><button disabled={busy} className="studio-secondary" onClick={()=>chooseLesson(l)}>Edit</button></div>)}</div><button disabled={busy} className="studio-primary" onClick={resetLesson}>Add another video</button></section>
    <form className="study-panel study-form" onSubmit={e=>{e.preventDefault();void save(true);}}><h2>2. {edit?'Edit lesson':'Import a YouTube video'}</h2><fieldset disabled={busy}><label>YouTube video link<input required type="url" value={form.url} disabled={edit} onChange={e=>{change('url',e.target.value);setPreview(null);}}/></label><button type="button" className="studio-secondary" disabled={!form.url} onClick={importVideo}>{busy?'Fetching…':'Fetch video details'}</button>{preview&&<img className="study-admin-preview" src={preview.thumbnail} alt="Imported YouTube video thumbnail"/>}<div className="study-admin-grid"><label>Unit<select value={form.unit} onChange={e=>change('unit',Number(e.target.value))}>{subject.units.map(u=><option key={u.number} value={u.number}>{u.number}. {u.title}</option>)}</select></label><label>Lesson order<input type="number" min="0" max="10000" value={form.order} onChange={e=>change('order',Number(e.target.value))}/></label></div><label>Display title<input required maxLength={200} value={form.title} onChange={e=>change('title',e.target.value)}/></label><label>Lesson summary<textarea maxLength={4000} value={form.summary} onChange={e=>change('summary',e.target.value)}/></label><div className="study-admin-grid"><label>Duration in minutes<input type="number" min="0" max="1440" step="any" value={form.minutes} onChange={e=>change('minutes',Number(e.target.value))}/></label><label>Mentor display name<input maxLength={100} value={form.mentorName} onChange={e=>change('mentorName',e.target.value)}/><small>This label does not grant account access. Mentor access comes from MENTOR_EMAILS on the backend.</small></label></div>
    <h2>3. Attach PDF notes & slides</h2><p>Attach public PDF links, including slides exported as PDF. Students can read them below the video.</p>{form.resources.map((r,i)=><div className="study-panel" key={i}><label>Resource title<input required maxLength={150} value={r.title} onChange={e=>change('resources',form.resources.map((v,j)=>j===i?{...v,title:e.target.value}:v))}/></label><label>Public HTTPS link<input required type="url" value={r.url} onChange={e=>change('resources',form.resources.map((v,j)=>j===i?{...v,url:e.target.value}:v))}/></label><label>Format<select value={r.format || 'link'} onChange={e=>change('resources',form.resources.map((v,j)=>j===i?{...v,format:e.target.value}:v))}><option value="pdf">PDF · read inside lesson</option><option value="link">Other resource link</option></select></label><label>Type<select value={r.kind} onChange={e=>change('resources',form.resources.map((v,j)=>j===i?{...v,kind:e.target.value}:v))}>{['notes','practice','past-paper','other'].map(k=><option key={k}>{k}</option>)}</select></label><button type="button" onClick={()=>change('resources',form.resources.filter((_,j)=>j!==i))}>Remove resource</button></div>)}<button type="button" className="studio-secondary" disabled={form.resources.length>=20} onClick={()=>change('resources',[...form.resources,{title:'',url:'',kind:'notes',format:'pdf'}])}>Add resource link</button>
    <h2>Optional lesson quiz</h2>{form.quiz.map((q,i)=><div className="study-panel" key={i}><label>Question {i+1}<textarea required maxLength={1000} value={q.question} onChange={e=>change('quiz',form.quiz.map((v,j)=>j===i?{...v,question:e.target.value}:v))}/></label>{q.options.map((o,k)=><label key={k}>Option {k+1}<input required maxLength={500} value={o} onChange={e=>change('quiz',form.quiz.map((v,j)=>j===i?{...v,options:v.options.map((x,n)=>n===k?e.target.value:x)}:v))}/></label>)}<label>Correct answer<select value={q.correct} onChange={e=>change('quiz',form.quiz.map((v,j)=>j===i?{...v,correct:Number(e.target.value)}:v))}>{[0,1,2,3].map(k=><option key={k} value={k}>Option {k+1}</option>)}</select></label><label>Explanation after submission<textarea required maxLength={2000} value={q.explanation} onChange={e=>change('quiz',form.quiz.map((v,j)=>j===i?{...v,explanation:e.target.value}:v))}/></label><button type="button" onClick={()=>change('quiz',form.quiz.filter((_,j)=>j!==i))}>Remove question</button></div>)}<button type="button" className="studio-secondary" disabled={form.quiz.length>=10} onClick={()=>change('quiz',[...form.quiz,{question:'',options:['','','',''],correct:0,explanation:''}])}>Add quiz question</button>
    <h2>Written chapter practice & previous-year questions</h2><p>Add the question and its model solution. For a previous-year question, include the exam, year and original paper link.</p>
    {form.practice.map((q,i)=>{const update=values=>change('practice',form.practice.map((v,j)=>i===j?{...v,...values}:v));return <div className="study-panel" key={q._id || i}><div className="study-admin-grid"><label>Question type<select value={q.type} onChange={e=>update({type:e.target.value})}><option value="short">Short answer</option><option value="long">Long answer</option><option value="numerical">Numerical</option></select></label><label>Marks (optional)<input type="number" min="0" max="100" value={q.marks || 0} onChange={e=>update({marks:Number(e.target.value)})}/></label></div><label>Question<textarea required maxLength={3000} value={q.question} onChange={e=>update({question:e.target.value})}/></label><label>Model solution / worked steps<textarea required maxLength={6000} rows={5} value={q.solution} onChange={e=>update({solution:e.target.value})}/></label><label>Question source<select value={q.isPYQ?'pyq':'mentor'} onChange={e=>update({isPYQ:e.target.value==='pyq'})}><option value="mentor">Mentor-written practice</option><option value="pyq">Previous-year exam question</option></select></label>{q.isPYQ&&<><label>Exam name<input required maxLength={150} value={q.exam || ''} onChange={e=>update({exam:e.target.value})}/></label><label>Exam year<input required type="number" min="2000" max={new Date().getFullYear()} value={q.year || ''} onChange={e=>update({year:Number(e.target.value)})}/></label><label>Original exam paper link<input required type="url" value={q.sourceUrl || ''} onChange={e=>update({sourceUrl:e.target.value})}/></label></>}<button type="button" onClick={()=>change('practice',form.practice.filter((_,j)=>j!==i))}>Remove practice question</button></div>;})}
    <button type="button" className="studio-secondary" disabled={form.practice.length>=20} onClick={()=>change('practice',[...form.practice,{type:'short',question:'',solution:'',marks:0,isPYQ:false,exam:'',year:0,sourceUrl:''}])}>Add written practice question</button>
    <h2>4. Preview & publish</h2>{preview&&<LecturePlayer videoId={preview.videoId} title={form.title}/>}<p><strong>{form.title || 'Your lesson title'}</strong> · {subject.title} · Unit {form.unit}</p><div className="study-row"><button type="button" className="studio-secondary" onClick={()=>save(false)}>{form.published?'Unpublish & save draft':'Save draft'}</button><button className="studio-primary">{busy?'Saving…':'Publish lesson'}</button></div></fieldset></form></>}
    </>}
  </div></main>;
}
