import { useEffect, useMemo, useState } from "react";
import { createAdminJob, deleteAdminJob, getAdminJobs, refreshAdminJob, updateAdminJob, updateAdminJobStatus } from "../Services/jobService";

const EMPTY = { title: "", company: "", officialUrl: "", sourceUrl: "", description: "", location: "", employmentType: "full-time", experienceLevel: "entry-level", salaryMin: "", salaryMax: "", deadline: "", sourceType: "official-company", sourceProvider: "" };
const STATUSES = ["all", "verified", "source_confirmed", "pending", "expired", "rejected"];
const SOURCE_TYPES = ["official-company", "greenhouse", "lever", "ashby", "workday", "partner-api", "admin-reviewed", "community-submitted", "other"];
const label = (value) => String(value || "").replaceAll("_", " ").replace(/\b\w/g, (character) => character.toUpperCase());

export default function AdminJobs() {
  const [jobs, setJobs] = useState([]); const [counts, setCounts] = useState(null); const [loading, setLoading] = useState(true); const [denied, setDenied] = useState(false); const [error, setError] = useState(""); const [filter, setFilter] = useState("all"); const [search, setSearch] = useState(""); const [formOpen, setFormOpen] = useState(false); const [form, setForm] = useState(EMPTY); const [editing, setEditing] = useState(null); const [saving, setSaving] = useState(false); const [preview, setPreview] = useState(null); const [success, setSuccess] = useState(null);
  const load = async () => { setLoading(true); try { const data = await getAdminJobs(); setJobs(data.jobs || []); setCounts(data.counts || null); setDenied(false); } catch (requestError) { if (requestError.response?.status === 403) setDenied(true); else setError(requestError.response?.data?.message || "Unable to load admin jobs."); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const visible = useMemo(() => jobs.filter((job) => { const status = job.verification?.status || "pending"; return (filter === "all" || status === filter) && `${job.title} ${job.company}`.toLowerCase().includes(search.toLowerCase()); }), [jobs, filter, search]);
  const update = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const startAdd = () => { setEditing(null); setForm(EMPTY); setSuccess(null); setFormOpen(true); };
  const startEdit = (job) => { setEditing(job); setForm({ title: job.title || "", company: job.company || "", officialUrl: job.application?.officialUrl || job.applyUrl || "", sourceUrl: job.source?.sourceUrl || "", description: job.description || "", location: typeof job.location === "string" ? job.location : job.location?.city || "", employmentType: job.employmentType || "full-time", experienceLevel: job.experienceLevel || "entry-level", salaryMin: job.salary?.min || "", salaryMax: job.salary?.max || "", deadline: job.deadline ? new Date(job.deadline).toISOString().slice(0, 10) : "", sourceType: job.source?.type || "official-company", sourceProvider: job.source?.provider || "" }); setFormOpen(true); };
  const submit = async (event) => { event.preventDefault(); setSaving(true); setError(""); const payload = { ...form, location: form.location || null, deadline: form.deadline || null, salary: form.salaryMin || form.salaryMax ? { min: Number(form.salaryMin) || null, max: Number(form.salaryMax) || null, currency: "INR", period: "year" } : null }; try { const job = editing ? await updateAdminJob(editing._id, payload) : await createAdminJob(payload); setSuccess(job); setFormOpen(false); await load(); } catch (requestError) { setError(requestError.response?.data?.message || "Unable to save this job. Your form is still here."); } finally { setSaving(false); } };
  const refresh = async (id) => { try { const job = await refreshAdminJob(id); setJobs((items) => items.map((item) => item._id === id ? job : item)); } catch { setError("Unable to refresh verification."); } };
  const setStatus = async (id, status) => { try { const job = await updateAdminJobStatus(id, status); setJobs((items) => items.map((item) => item._id === id ? job : item)); await load(); } catch (requestError) { setError(requestError.response?.data?.message || "Unable to update verification."); } };
  const remove = async (job) => { if (!window.confirm(`Delete ${job.title} at ${job.company}?`)) return; try { await deleteAdminJob(job._id); setJobs((items) => items.filter((item) => item._id !== job._id)); await load(); } catch { setError("Unable to delete this job."); } };
  if (loading) return <main className="min-h-screen bg-[#111827] px-5 py-14 text-white"><div className="mx-auto h-64 max-w-6xl animate-pulse rounded-xl bg-white/10"/></main>;
  if (denied) return <main className="grid min-h-screen place-items-center bg-[#111827] px-5 text-center text-white"><div><p className="text-xs font-extrabold uppercase tracking-widest text-orange-400">Admin jobs</p><h1 className="mt-3 text-3xl font-black">Access denied</h1><p className="mt-3 max-w-md text-sm leading-6 text-slate-300">This area is available only to authorized Newbert administrators.</p></div></main>;
  return <main className="min-h-screen bg-[#111827] px-5 py-12 text-white md:py-16"><div className="mx-auto max-w-6xl"><header className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-extrabold uppercase tracking-[.2em] text-orange-400">Admin</p><h1 className="mt-3 text-3xl font-black md:text-5xl">Admin Jobs</h1><p className="mt-3 text-sm text-slate-300">Manage verified opportunities shown on Newbert.</p></div><button onClick={startAdd} className="rounded-lg bg-orange-500 px-4 py-3 text-sm font-extrabold text-slate-950">+ Add New Job</button></header>{error && <p className="mt-5 rounded-lg border border-red-400/30 bg-red-400/10 px-4 py-3 text-sm font-semibold text-red-200">{error}</p>}{success && <Success job={success} onPreview={() => setPreview(success)} onAdd={startAdd}/>}<section className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Summary label="Total jobs" value={counts?.total ?? jobs.length}/><Summary label="Verified" value={counts?.verified ?? 0}/><Summary label="Source confirmed" value={counts?.sourceConfirmed ?? 0}/><Summary label="Pending" value={counts?.pending ?? 0}/><Summary label="Expired" value={counts?.expired ?? 0}/></section><section className="mt-9 border-y border-white/10 py-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div className="flex flex-wrap gap-2">{STATUSES.map((status) => <button key={status} onClick={() => setFilter(status)} className={`rounded-lg px-3 py-2 text-sm font-bold ${filter === status ? "bg-orange-500 text-slate-950" : "border border-white/10 text-slate-300"}`}>{label(status)}</button>)}</div><input value={search} onChange={(event) => setSearch(event.target.value)} className="rounded-lg border border-white/10 bg-[#172033] px-3 py-2 text-sm text-white outline-none focus:border-orange-400" placeholder="Search company or title"/></div></section><section className="mt-6 space-y-3">{visible.map((job) => <JobRow key={job._id} job={job} onPreview={() => setPreview(job)} onEdit={() => startEdit(job)} onRefresh={() => refresh(job._id)} onStatus={(status) => setStatus(job._id, status)} onDelete={() => remove(job)}/>) || null}{!visible.length && <p className="rounded-xl border border-dashed border-white/15 p-10 text-center text-slate-300">No jobs match this filter.</p>}</section></div>{formOpen && <JobForm form={form} update={update} editing={Boolean(editing)} loading={saving} onClose={() => setFormOpen(false)} onSubmit={submit}/>} {preview && <Preview job={preview} onClose={() => setPreview(null)}/>}</main>;
}
function Summary({ label: text, value }) { return <div className="rounded-lg border border-white/10 bg-[#172033] p-4"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">{text}</p><p className="mt-2 text-2xl font-black text-orange-300">{value}</p></div>; }
function Badge({ status }) { const tones = { verified: "bg-emerald-400/15 text-emerald-300", source_confirmed: "bg-orange-400/15 text-orange-200", pending: "bg-amber-400/15 text-amber-200", expired: "bg-slate-400/15 text-slate-300", rejected: "bg-red-400/15 text-red-200" }; return <span className={`rounded-full px-2.5 py-1 text-xs font-extrabold ${tones[status] || tones.pending}`}>{label(status)}</span>; }
function JobRow({ job, onPreview, onEdit, onRefresh, onStatus, onDelete }) { const status = job.verification?.status || "pending"; return <article className="rounded-xl border border-white/10 bg-[#172033] p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-xs font-extrabold uppercase tracking-widest text-orange-300">{job.company}</p><h2 className="mt-1 text-lg font-black">{job.title}</h2><p className="mt-2 text-xs text-slate-400">{job.source?.provider || job.source?.type || "Unknown source"} · Last checked {job.verification?.lastCheckedAt ? new Date(job.verification.lastCheckedAt).toLocaleString() : "Never"}{job.deadline ? ` · Deadline ${new Date(job.deadline).toLocaleDateString()}` : ""}</p></div><div className="flex flex-wrap items-center gap-2"><Badge status={status}/><button onClick={onPreview} className="text-xs font-extrabold text-slate-200">Preview</button><button onClick={onEdit} className="text-xs font-extrabold text-orange-300">Edit</button><button onClick={onRefresh} className="text-xs font-extrabold text-orange-300">Refresh</button><select value={status} onChange={(event) => onStatus(event.target.value)} className="rounded-md border border-white/10 bg-[#111827] px-2 py-1 text-xs font-bold text-white">{STATUSES.slice(1).map((item) => <option key={item} value={item}>{label(item)}</option>)}</select><button onClick={onDelete} className="text-xs font-extrabold text-red-300">Delete</button></div></div></article>; }
function JobForm({ form, update, editing, loading, onClose, onSubmit }) { return <div className="fixed inset-0 z-[70] overflow-y-auto bg-black/60 p-5"><form onSubmit={onSubmit} className="mx-auto my-8 max-w-3xl rounded-xl border border-white/10 bg-[#172033] p-6 text-white"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-extrabold uppercase tracking-widest text-orange-400">{editing ? "Edit job" : "Add verified job"}</p><h2 className="mt-2 text-2xl font-black">{editing ? "Correct job details" : "Add a new opportunity"}</h2></div><button type="button" onClick={onClose} className="text-sm font-bold text-slate-300">Close</button></div><p className="mt-3 text-sm text-slate-300">Paste the job description from the official company career page or trusted ATS source.</p><div className="mt-6 grid gap-4 sm:grid-cols-2"><Field label="Job title *" value={form.title} onChange={(value) => update("title", value)}/><Field label="Company *" value={form.company} onChange={(value) => update("company", value)}/><Field label="Official apply URL *" value={form.officialUrl} onChange={(value) => update("officialUrl", value)} type="url"/><Field label="Source URL" value={form.sourceUrl} onChange={(value) => update("sourceUrl", value)} type="url"/><Field label="Location" value={form.location} onChange={(value) => update("location", value)}/><Select label="Employment type" value={form.employmentType} onChange={(value) => update("employmentType", value)} options={["full-time", "internship", "part-time", "contract"]}/><Select label="Experience level" value={form.experienceLevel} onChange={(value) => update("experienceLevel", value)} options={["intern", "entry-level", "junior", "mid", "senior", "unspecified"]}/><Field label="Deadline" value={form.deadline} onChange={(value) => update("deadline", value)} type="date"/><Field label="Salary min" value={form.salaryMin} onChange={(value) => update("salaryMin", value)} type="number"/><Field label="Salary max" value={form.salaryMax} onChange={(value) => update("salaryMax", value)} type="number"/><Select label="Source type" value={form.sourceType} onChange={(value) => update("sourceType", value)} options={SOURCE_TYPES}/><Field label="Source provider" value={form.sourceProvider} onChange={(value) => update("sourceProvider", value)}/></div><label className="mt-4 block text-sm font-extrabold text-slate-200">Job description *<textarea required value={form.description} onChange={(event) => update("description", event.target.value)} rows="10" className="mt-2 w-full resize-y rounded-lg border border-white/10 bg-[#111827] p-3 text-sm text-white outline-none focus:border-orange-400"/></label><button disabled={loading} className="mt-6 rounded-lg bg-orange-500 px-5 py-3 text-sm font-extrabold text-slate-950 disabled:opacity-50">{loading ? "Verifying source, analyzing job description, saving job…" : editing ? "Save changes" : "Analyze & Add Job"}</button></form></div>; }
function Field({ label: text, value, onChange, type = "text" }) { return <label className="text-sm font-extrabold text-slate-200">{text}<input required={text.includes("*")} type={type} value={value} onChange={(event) => onChange(event.target.value)} className="mt-2 w-full rounded-lg border border-white/10 bg-[#111827] p-3 text-sm font-medium text-white outline-none focus:border-orange-400"/></label>; }
function Select({ label: text, value, onChange, options }) { return <label className="text-sm font-extrabold text-slate-200">{text}<select value={value} onChange={(event) => onChange(event.target.value)} className="mt-2 w-full rounded-lg border border-white/10 bg-[#111827] p-3 text-sm font-medium text-white">{options.map((option) => <option key={option} value={option}>{label(option)}</option>)}</select></label>; }
function Preview({ job, onClose }) { return <div className="fixed inset-0 z-[80] grid place-items-center bg-black/60 p-5"><section className="w-full max-w-lg rounded-xl border border-white/10 bg-[#172033] p-6 text-white"><div className="flex justify-between"><div><p className="text-xs font-extrabold uppercase tracking-widest text-orange-400">Student preview</p><h2 className="mt-2 text-2xl font-black">{job.title}</h2><p className="mt-1 text-slate-300">{job.company} · {typeof job.location === "string" ? job.location : job.location?.city || "Location not listed"}</p></div><button onClick={onClose} className="text-slate-300">Close</button></div><div className="mt-5"><Badge status={job.verification?.status || "pending"}/><p className="mt-4 text-sm text-slate-300">{job.description}</p></div><div className="mt-5 flex flex-wrap gap-2">{(job.requirements?.requiredSkills || job.skills || []).map((skill) => <span key={skill} className="rounded-md bg-orange-400/10 px-2 py-1 text-xs font-bold text-orange-200">{skill}</span>)}</div><a href={job.application?.officialUrl || job.applyUrl} target="_blank" rel="noreferrer" className="mt-6 inline-flex rounded-lg bg-orange-500 px-4 py-3 text-sm font-extrabold text-slate-950">Official apply link</a></section></div>; }
function Success({ job, onPreview, onAdd }) { return <section className="mt-6 rounded-xl border border-emerald-400/30 bg-emerald-400/10 p-5"><p className="font-extrabold text-emerald-200">Job added successfully.</p><p className="mt-1 text-sm text-slate-300">Verification: {label(job.verification?.status)} · Required skills detected: {(job.requirements?.requiredSkills || []).join(" · ") || "None automatically detected"}</p><div className="mt-3 flex gap-3"><button onClick={onPreview} className="text-sm font-extrabold text-emerald-200">Preview job</button><button onClick={onAdd} className="text-sm font-extrabold text-orange-300">Add another</button></div></section>; }
