import {useEffect,useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import {ArrowRight,Check,MessageSquare,ShieldCheck} from 'lucide-react';
import useAuth from '../hook/useAuth';
import API from '../Services/api';
import QuestionRenderer from '../components/AlumniChat/QuestionRenderer';
import AlumniReview,{PrivateEvidence} from '../components/AlumniChat/AlumniReview';
import {AnswerValue} from '../components/AlumniChat/AnswerFields';
import '../alumni-chat.css';

export default function AlumniOnboarding(){const {user,profile,isAuthenticated}=useAuth();const scope=profile?.userId||user?.id||user?.email;return <main className="alumni-chat-page"><div className="ac-shell"><Link className="ac-back" to="/alumni-wall">← Alumni Wall</Link>{isAuthenticated?<Conversation key={scope} scope={scope} name={profile?.name||user?.name||'there'}/>:<section className="ac-welcome"><p className="ac-kicker">NEWBERT ALUMNI NETWORK</p><h1>Your experience.<br/><em>Someone’s next step.</em></h1><p>Share the choices, preparation and lessons that shaped your journey. Sign in to save your conversation and choose what juniors can see.</p><p className="ac-note">Use “Sign in” in the navigation above. You will return to this conversation.</p></section>}</div></main>;}
function Conversation({scope,name}){
 const [data,setData]=useState(null);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [view,setView]=useState('welcome');const [editing,setEditing]=useState(null);const [preview,setPreview]=useState(null);const [restart,setRestart]=useState(false);const [hideConfirm,setHideConfirm]=useState(false);const alive=useRef(true);
 const session=data?.session;const question=editing||session?.currentQuestion;
 useEffect(()=>{alive.current=true;const controller=new AbortController();API.get('/alumni-chat/session',{signal:controller.signal}).then(({data:result})=>{if(alive.current)setData(result);}).catch(e=>{if(e.code!=='ERR_CANCELED'&&alive.current)setError(e.response?.data?.message||'Your saved conversation could not be loaded.');}).finally(()=>{if(alive.current)setLoading(false);});return()=>{alive.current=false;controller.abort();};},[]);
 async function review(){setBusy(true);setError('');try{const {data:result}=await API.get('/alumni-chat/review');if(!alive.current)return;setData(result);setPreview(result.preview);setEditing(null);setView('review');}catch(e){if(alive.current)setError(e.response?.data?.message||'Review could not be loaded. Your answers are still saved.');}finally{if(alive.current)setBusy(false);}}
 async function mutate(path,payload={},returnReview=false){if(busy)return;setBusy(true);setError('');setNotice('');try{const {data:result}=await API.post(`/alumni-chat/${path}`,{version:session?.version,...payload});if(!alive.current)return;setData(result);setNotice(result.notice||'');setEditing(null);if(returnReview){const {data:reviewed}=await API.get('/alumni-chat/review');if(!alive.current)return;setData(reviewed);setPreview(reviewed.preview);setView('review');}else setView(result.session?.status==='COMPLETED'?'published':result.session?.currentQuestion?'chat':'review');if(!result.session?.currentQuestion&&result.session?.status!=='COMPLETED'){const {data:reviewed}=await API.get('/alumni-chat/review');if(alive.current){setData(reviewed);setPreview(reviewed.preview);}}}catch(e){if(alive.current)setError(e.response?.data?.message||'Your answer could not be saved. Keep this page open and try again.');}finally{if(alive.current)setBusy(false);}}
 async function reload(){setError('');try{const {data:result}=await API.get('/alumni-chat/session');setData(result);setEditing(null);setView('welcome');}catch{setError('Could not reconnect. Please try again.');}}
 const completed=session?.completed||0;
 return <><header className="ac-header"><div><span className="ac-wordmark">N</span><div><strong>Newbert Alumni Assistant</strong><small>Your story. One conversation.</small></div></div><span className="ac-private"><ShieldCheck size={14}/>Private until you publish</span></header>
 {error&&<div className="ac-alert" role="alert">{error}<button onClick={reload} disabled={busy}>Reload saved conversation</button></div>}{notice&&<div className="ac-notice" role="status">{notice}</div>}
 {loading?<p className="ac-loading">Finding your saved conversation…</p>:view==='welcome'?<section className="ac-welcome"><p className="ac-kicker">NEWBERT ALUMNI NETWORK</p><h1>{completed?`Welcome back, ${name.split(' ')[0]}.`:`Hi ${name.split(' ')[0]},`}<br/><em>{completed?'Your story is waiting.':'make the path clearer.'}</em></h1><p>Your experience can help juniors understand what actually worked for someone who has already gone through the journey.</p><div className="ac-welcome-points"><span><MessageSquare size={18}/>One question at a time</span><span><Check size={18}/>Save, leave and resume</span><span><ShieldCheck size={18}/>You choose what is shared</span></div>{completed>0&&<p><strong>{session.progress}% complete</strong> · {completed} answers recorded</p>}<button className="ac-primary" disabled={busy} onClick={()=>mutate('start')}>{busy?'Opening your conversation…':session?.status==='COMPLETED'?'Manage my published story':completed?'Continue my story':'Start my story'}<ArrowRight size={17}/></button><p className="ac-note">Optional questions can be skipped. Every answer can be edited before publication.</p></section>:view==='published'?<section className="ac-welcome"><p className="ac-kicker">YOUR JOURNEY IS LIVE</p><h1>A clearer path<br/><em>for the next student.</em></h1><p>Your story is published with the visibility settings you chose. Your outcome is labelled self-reported until independently verified.</p><div className="ac-actions"><Link className="ac-primary" to={`/alumni-wall/${session.publishedAlumniId}`}>View my alumni profile</Link><button className="ac-secondary" onClick={review}>Edit my story</button><button onClick={()=>setHideConfirm(true)}>Hide from Alumni Wall</button></div>{hideConfirm&&<div className="ac-alert"><p>Hide your published story? Your saved answers remain available.</p><button onClick={async()=>{try{await API.post('/alumni-chat/hide',{confirm:true});setNotice('Your story is hidden. Review and publish again whenever you are ready.');setHideConfirm(false);await review();}catch(e){setError(e.response?.data?.message||'Could not hide your story.');}}}>Confirm hide</button><button onClick={()=>setHideConfirm(false)}>Cancel</button></div>}</section>:<>
 <section className="ac-progress" aria-label="Conversation progress"><div><strong>{session?.progress||0}% complete</strong><span>{completed} of {session?.total||0} relevant questions</span></div><progress max="100" value={session?.progress||0}/><div className="ac-sections">{session?.sections.map(section=><button key={section.name} aria-current={question?.section===section.name?'step':undefined} disabled={busy} onClick={()=>{setEditing(session.questions.find(q=>q.section===section.name&&!Object.hasOwn(session.answers,q.id))||session.questions.find(q=>q.section===section.name));setView('chat');}}>{section.completed===section.total?'✓ ':''}{section.name}</button>)}</div><button className="ac-review-link" onClick={review} disabled={busy}>Review answers & privacy →</button></section>
 {session?.prefill&&Object.keys(session.prefill).length>0?<section className="ac-prefill"><p className="ac-kicker">A HEAD START FROM YOUR PROFILE</p><h2>I found a few details you have already shared.</h2><p>Check them before bringing them into your alumni story.</p><AnswerValue value={session.prefill}/><div className="ac-actions"><button className="ac-secondary" disabled={busy} onClick={()=>mutate('prefill',{use:false})}>Enter details myself</button><button className="ac-primary" disabled={busy} onClick={()=>mutate('prefill',{use:true})}>Use these details</button></div></section>:view==='review'?<AlumniReview session={session} preview={preview} busy={busy} onEdit={q=>{setEditing(q);setView('chat');}} onPublish={()=>mutate('publish',{confirm:true})} onContinue={()=>{setEditing(null);setView(session.currentQuestion?'chat':'review');}}/>:question?<>
 {completed>0&&<details className="ac-transcript"><summary>Your saved conversation · {completed} answers</summary>{session.questions.filter(q=>Object.hasOwn(session.answers,q.id)).map(q=><article key={q.id}><p><strong>Newbert:</strong> {q.text}</p><div className="ac-user-answer"><AnswerValue value={session.answers[q.id]}/></div><button onClick={()=>setEditing(q)}>Edit this answer</button></article>)}</details>}
 <QuestionRenderer key={`${question.id}:${session.version}`} question={question} session={session} scope={scope} privacyFields={data.privacyFields||[]} busy={busy} returnToReview={Boolean(editing)} onAnswer={(id,value)=>mutate('answer',{questionId:id,value},Boolean(editing))} onExtract={(id,rawAnswer)=>mutate('extract',{questionId:id,rawAnswer})} onConfirm={value=>mutate('confirm-extraction',{value},Boolean(editing))} onSkip={id=>mutate('skip',{questionId:id},Boolean(editing))} onBack={()=>mutate('back')}/>{question.section==='Verification'&&<PrivateEvidence/>}</>:null}
 <footer className="ac-footer"><p>Your account keeps submitted answers. Use review to jump to any remaining required answer.</p><button disabled={busy} onClick={()=>setRestart(true)}>Restart draft</button>{restart&&<div className="ac-alert"><p>Start a fresh draft? This clears this conversation’s saved answers. Your published story and evidence documents remain unchanged.</p><button disabled={busy} onClick={()=>{setRestart(false);mutate('restart',{confirm:true});}}>Restart my draft</button><button onClick={()=>setRestart(false)}>Keep my answers</button></div>}</footer>
 </>}</>;
}
