import { useState } from "react";
import { useNavigate } from "react-router-dom";

const proof = [["40+", "AKTU colleges"], ["500+", "alumni stories"], ["2,000+", "students guided"], ["6 LPA", "average package"]];
const path = [["01", "Your current profile", "Skills, DSA, projects, college and target role."], ["02", "A senior who made it", "A real outcome from the same kind of starting point."], ["03", "The gap AI can explain", "What is missing, what matters first, and how to close it."]];

export default function Home() {
  const navigate = useNavigate();
  const [storyStep, setStoryStep] = useState(0);
  return <main className="home-page bg-[#171918] text-white">
    <section className="home-hero relative overflow-hidden border-b border-white/10 px-5 pb-16 pt-20 md:pb-24 md:pt-28">
      <div className="home-sky" aria-hidden="true"><span className="home-orb"/><span className="home-cloud home-cloud-one"/><span className="home-cloud home-cloud-two"/></div>
      <div className="pointer-events-none absolute inset-0 opacity-20 [background-image:radial-gradient(#ffffff_1px,transparent_1px)] [background-size:28px_28px]" />
      <span className="home-marker home-marker-one">&lt;/&gt;</span><span className="home-marker home-marker-two">{`{ }`}</span><span className="home-marker home-marker-three">01</span>
      <div className="relative mx-auto max-w-6xl text-center"><p className="text-xs font-extrabold uppercase tracking-[0.22em] text-orange-400">Track. Compare. Get placed.</p><h1 className="mx-auto mt-6 max-w-4xl text-4xl font-extrabold leading-tight tracking-tight md:text-7xl">Stop guessing.<br/>See exactly what got <span className="text-orange-400">your seniors placed.</span></h1><p className="mx-auto mt-6 max-w-2xl text-base leading-7 text-slate-300 md:text-lg">Real placement journeys from students at your college. Not generic advice. Not IIT stories. Your college. Your truth.</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><button onClick={() => navigate("/alumni-wall")} className="rounded-md bg-orange-500 px-5 py-3 text-sm font-extrabold text-white transition hover:bg-orange-400">See alumni from your college</button><button onClick={() => navigate("/roadmap")} className="rounded-md border border-white/25 bg-white/5 px-5 py-3 text-sm font-extrabold text-white transition hover:border-orange-400">Check your current gap</button></div>
        <div className="mx-auto mt-12 grid max-w-4xl grid-cols-2 gap-px overflow-hidden border border-white/10 bg-white/10 md:grid-cols-4">{proof.map(([number, label]) => <div key={label} className="bg-[#171918] px-3 py-5"><p className="text-2xl font-extrabold text-orange-400">{number}</p><p className="mt-1 text-xs text-slate-400">{label}</p></div>)}</div>
      </div>
    </section>

    <section className="relative overflow-hidden border-b border-white/10 bg-[#20231f] px-5 py-20 md:py-28"><div className="mx-auto grid max-w-6xl gap-10 md:grid-cols-[.8fr_1.2fr] md:items-center"><AdityaSignalPanel step={storyStep} onStep={setStoryStep}/><div><p className="text-xs font-extrabold uppercase tracking-[0.2em] text-orange-400">A story you know</p><h2 className="mt-4 text-3xl font-extrabold leading-tight md:text-5xl">Meet Aditya.<br/><span className="text-orange-400">Third year. AKTU.</span></h2><div className="mt-7 space-y-5 border-l border-white/15 pl-5"><Story title="40 applications. 38 rejections." text="Every senior has a different opinion: grind DSA, learn development, make projects. Nothing tells him what is actually missing."/><Story title="He is not behind. He cannot see the gap." text="No one has shown him the real path from his college to a job like the one he wants."/><Story title="Newbert makes that path visible." text="He compares himself with seniors, sees the gap, and gets a plan built around it." active/></div></div></div></section>

    <section className="border-b border-white/10 px-5 py-20 md:py-28"><div className="mx-auto max-w-6xl"><div className="max-w-2xl"><p className="text-xs font-extrabold uppercase tracking-[0.2em] text-orange-400">The Newbert loop</p><h2 className="mt-4 text-3xl font-extrabold leading-tight md:text-5xl">The answer is already in the journeys around you.</h2></div><div className="mt-12 grid gap-5 md:grid-cols-3">{path.map(([number,title,description]) => <article key={number} className="group border-t-2 border-orange-400 pt-5"><p className="font-mono text-sm text-orange-300">{number}</p><h3 className="mt-5 text-xl font-extrabold">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{description}</p><div className="mt-7 h-px w-12 bg-white/20 transition-all duration-500 group-hover:w-full group-hover:bg-orange-400"/></article>)}</div>
      <div className="mt-16 overflow-hidden border border-white/10 bg-[#20231f]"><div className="grid md:grid-cols-[1fr_auto_1fr]"><ProfileMini heading="You, today" name="Anant" meta="AKTU · CSE · 2026" stats={["124 DSA", "2 projects", "React"]}/><div className="home-compare-line flex items-center justify-center px-5 py-7 text-center"><span className="rounded-full border border-orange-400/40 bg-orange-500/10 px-4 py-2 text-xs font-bold text-orange-300">AI compares</span></div><ProfileMini heading="Placed senior" name="Rahul Kumar" meta="AKTU · TCS Digital" stats={["280 DSA", "3 projects", "React + Node"]}/></div><div className="border-t border-white/10 px-6 py-5"><p className="text-xs font-bold uppercase tracking-[0.12em] text-orange-400">What Newbert tells you next</p><p className="mt-2 text-sm text-slate-300">Your strongest next move is one deployed full-stack project plus 60 medium DSA problems. This closes the largest gap with the seniors you match.</p></div></div>
    </div></section>

    <section className="bg-orange-500 px-5 py-16 text-[#171918] md:py-20"><div className="mx-auto flex max-w-6xl flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="text-xs font-extrabold uppercase tracking-[0.2em]">No more blind preparation</p><h2 className="mt-3 max-w-2xl text-3xl font-extrabold leading-tight md:text-5xl">Start with your current situation. Build towards your next offer.</h2></div><div className="flex gap-3"><button onClick={() => navigate("/profile")} className="rounded-md bg-[#171918] px-5 py-3 text-sm font-extrabold text-white hover:bg-black">Build my profile</button><button onClick={() => navigate("/jobs")} className="rounded-md border border-[#171918]/50 px-5 py-3 text-sm font-extrabold hover:bg-orange-400">See AI job matches</button></div></div></section>
  </main>;
}
function Story({ title, text, active = false }) { return <article className="relative"><span className={`absolute -left-[25px] top-1 h-2.5 w-2.5 rounded-full ${active ? "bg-orange-400 shadow-[0_0_16px_3px_rgba(251,146,60,.35)]" : "bg-slate-500"}`}/><h3 className="font-bold text-white">{title}</h3><p className="mt-1 text-sm leading-6 text-slate-400">{text}</p></article>; }
function ProfileMini({ heading, name, meta, stats }) { return <div className="p-6"><p className="text-xs font-bold uppercase tracking-[0.14em] text-slate-500">{heading}</p><p className="mt-3 text-lg font-extrabold">{name}</p><p className="mt-1 text-sm text-slate-400">{meta}</p><div className="mt-5 flex flex-wrap gap-2">{stats.map((stat) => <span key={stat} className="border border-white/10 bg-white/5 px-2 py-1 text-xs font-semibold text-slate-300">{stat}</span>)}</div></div>; }
function AdityaSignalPanel({ step, onStep }) {
  const screens = [
    { eyebrow: "Before Newbert", title: "Applied to 40 roles", value: "38", label: "rejections", note: "The advice is everywhere, but it is not specific to his profile.", bars: [32, 50, 24, 42] },
    { eyebrow: "Senior comparison", title: "Rahul got TCS Digital", value: "68%", label: "current match", note: "Same college. Same branch. The difference is now visible.", bars: [70, 42, 65, 88] },
    { eyebrow: "AI gap insight", title: "Here is what to do next", value: "2", label: "high-impact gaps", note: "One deployed project and 60 medium DSA problems can move his match forward.", bars: [70, 72, 86, 90] },
  ];
  const active = screens[step];
  return <div className="mx-auto w-full max-w-sm border border-white/15 bg-[#171918] p-4 shadow-2xl"><div className="flex items-center justify-between border-b border-white/10 pb-3"><div className="flex gap-1.5"><span className="h-2 w-2 rounded-full bg-orange-400"/><span className="h-2 w-2 rounded-full bg-white/20"/><span className="h-2 w-2 rounded-full bg-white/20"/></div><p className="font-mono text-[10px] text-slate-500">ADITYA / PLACEMENT SIGNAL</p></div><div className="p-4"><p className="text-[10px] font-extrabold uppercase tracking-[0.16em] text-orange-400">{active.eyebrow}</p><h3 className="mt-2 text-lg font-extrabold text-white">{active.title}</h3><div className="mt-6 flex items-end gap-2"><p className="text-5xl font-extrabold text-orange-400">{active.value}</p><p className="pb-1 text-xs font-bold uppercase tracking-wide text-slate-400">{active.label}</p></div><div className="mt-6 flex h-20 items-end gap-2 border-b border-white/10 pb-2">{active.bars.map((height, index) => <span key={index} style={{ height: `${height}%` }} className="home-signal-bar flex-1 bg-orange-400/80"/>)}</div><p className="mt-5 text-sm leading-6 text-slate-300">{active.note}</p></div><div className="grid grid-cols-3 gap-px border-t border-white/10 bg-white/10">{screens.map((screen, index) => <button key={screen.eyebrow} onClick={() => onStep(index)} className={`px-2 py-3 text-[10px] font-bold uppercase tracking-wide transition ${step === index ? "bg-orange-500 text-white" : "bg-[#171918] text-slate-400 hover:text-white"}`}>Step {index + 1}</button>)}</div></div>;
}
