import { useEffect, useMemo, useState } from "react";
import useAuth from "../hook/useAuth";
import { getJobAnalysis, getRecommendedJobs, listVerifiedJobs, saveJobForUser, unsaveJobForUser } from "../Services/jobService";

const TABS = [["for_you", "For You"], ["apply_today", "Apply Today"], ["within_reach", "Within Reach"], ["all", "All Verified"], ["saved", "Saved"]];
const locationLabel = (location) => !location ? "Location not listed" : typeof location === "string" ? location : [location.city, location.state, location.country, location.remoteType].filter(Boolean).join(" · ") || "Location not listed";

export default function Jobs() {
  const { isAuthenticated } = useAuth();
  const [tab, setTab] = useState("for_you"); const [query, setQuery] = useState(""); const [type, setType] = useState("");
  const [records, setRecords] = useState([]); const [context, setContext] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [analysis, setAnalysis] = useState(null); const [analyzing, setAnalyzing] = useState(false);
  useEffect(() => { let active = true; setLoading(true); const params = { search: query || undefined, employmentType: type || undefined }; const request = isAuthenticated ? getRecommendedJobs(params) : listVerifiedJobs(params).then((jobs) => ({ jobs: jobs.map((job) => ({ job, match: null, saved: null })), context: null })); request.then((data) => { if (active) { setRecords(data.jobs || []); setContext(data.context || null); setError(""); } }).catch((requestError) => { if (active) setError(requestError.response?.data?.message || "Unable to load verified jobs."); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [isAuthenticated, query, type]);
  const shown = useMemo(() => records.filter((record) => tab === "all" || (tab === "saved" ? Boolean(record.saved) : tab === "for_you" ? record.match?.eligible && record.match.bucket !== "not_ready" : record.match?.bucket === tab)), [records, tab]);
  const signals = context ? [context.goal, ...(context.skills || []).slice(0, 3), context.dsaSolved != null ? `${context.dsaSolved} DSA` : null, context.projects != null ? `${context.projects} Projects` : null].filter(Boolean) : [];
  const analyze = async (record) => { if (!isAuthenticated) return setError("Sign in to compare a job with your profile."); setAnalyzing(true); setAnalysis({}); try { setAnalysis(await getJobAnalysis(record.job._id)); } catch (requestError) { setAnalysis(null); setError(requestError.response?.data?.message || "Unable to analyze this job."); } finally { setAnalyzing(false); } };
  const save = async (record) => { if (!isAuthenticated) return setError("Sign in to save a job."); try { if (record.saved) await unsaveJobForUser(record.job._id); else await saveJobForUser(record.job._id); setRecords((items) => items.map((item) => item.job._id === record.job._id ? { ...item, saved: item.saved ? null : { status: "saved" } } : item)); } catch { setError("Unable to update saved jobs."); } };
  return <main className="min-h-screen bg-[#111827] px-5 py-12 text-white md:py-16"><div className="mx-auto max-w-6xl"><header className="max-w-3xl"><p className="text-xs font-extrabold uppercase tracking-[.2em] text-orange-400">Verified opportunities</p><h1 className="mt-3 text-3xl font-black md:text-5xl">Jobs For You</h1><p className="mt-4 text-sm leading-6 text-slate-300">Verified opportunities ranked by your actual readiness, skills, projects and career goal.</p>{signals.length ? <div className="mt-5 flex flex-wrap gap-2 text-xs font-bold text-orange-200"><span className="text-slate-400">Based on:</span>{signals.map((signal) => <span key={signal} className="rounded-full border border-orange-400/30 bg-orange-400/10 px-2.5 py-1">{signal}</span>)}</div> : null}</header><section className="mt-8 flex flex-col gap-4 border-y border-white/10 py-4 lg:flex-row lg:items-center lg:justify-between"><div className="flex flex-wrap gap-2">{TABS.map(([value, label]) => <button key={value} onClick={() => setTab(value)} className={`rounded-lg px-3 py-2 text-sm font-bold ${tab === value ? "bg-orange-500 text-slate-950" : "border border-white/10 text-slate-300"}`}>{label}</button>)}</div><div className="flex gap-2"><select value={type} onChange={(event) => setType(event.target.value)} className="rounded-lg border border-white/10 bg-[#172033] px-3 text-sm font-bold text-white"><option value="">All types</option><option value="internship">Internship</option><option value="full-time">Full time</option></select><input value={query} onChange={(event) => setQuery(event.target.value)} className="min-w-0 rounded-lg border border-white/10 bg-[#172033] px-3 py-2 text-sm text-white outline-none focus:border-orange-400" placeholder="Role or company"/></div></section>{error && <p className="mt-5 rounded-lg border border-red-400/30 bg-red-400/10 px-4 py-3 text-sm font-semibold text-red-200">{error}</p>}{loading ? <div className="mt-6 grid gap-4 md:grid-cols-2">{[1, 2, 3, 4].map((item) => <div key={item} className="h-56 animate-pulse rounded-xl bg-white/10"/>)}</div> : <div className="mt-6 grid gap-4 md:grid-cols-2">{shown.map((record) => <JobCard key={record.job._id} record={record} onAnalyze={() => analyze(record)} onSave={() => save(record)}/>)}</div>}{!loading && !shown.length && <div className="mt-6 rounded-xl border border-dashed border-white/15 p-10 text-center text-slate-300">No verified jobs match this view yet.</div>}</div>{(analysis || analyzing) && <JobAnalysisModal analysis={analysis} loading={analyzing} onClose={() => setAnalysis(null)}/>}</main>;
}

function JobCard({ record, onAnalyze, onSave }) { const { job, match, saved } = record; const gaps = match?.gaps || {}; const verificationStatus = job.verification?.status || "pending"; const verified = verificationStatus === "verified"; const verificationLabel = verified ? "✓ Verified" : verificationStatus === "source_confirmed" ? "Source confirmed" : "Verification pending"; return <article className="rounded-xl border border-white/10 bg-[#172033] p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-extrabold uppercase tracking-widest text-orange-300">{job.company}</p><h2 className="mt-2 text-xl font-black">{job.title}</h2><p className="mt-2 text-sm text-slate-300">{locationLabel(job.location)} · {job.employmentType}</p></div>{match?.overallScore != null && <span className="rounded-lg bg-orange-400 px-2.5 py-1.5 text-sm font-black text-slate-950">{match.overallScore}%</span>}</div><div className="mt-4 flex flex-wrap gap-2 text-xs font-bold"><span className={`rounded-full px-2.5 py-1 ${verified ? "bg-emerald-400/15 text-emerald-300" : "bg-orange-400/15 text-orange-200"}`}>{verificationLabel}</span>{job.verification?.lastCheckedAt && <span className="text-slate-400">Last checked {new Date(job.verification.lastCheckedAt).toLocaleDateString()}</span>}</div>{match && <><p className={`mt-4 text-sm font-extrabold ${match.eligible ? "text-emerald-300" : "text-red-300"}`}>{match.eligible ? match.bucket === "apply_today" ? "Apply today" : match.withinReachDays ? `Within reach in ~${match.withinReachDays} days` : "Not ready yet" : "Eligibility needs attention"}</p><div className="mt-3 flex flex-wrap gap-2">{match.matchedRequirements.slice(0, 3).map((skill) => <span key={skill} className="rounded-md bg-emerald-400/10 px-2 py-1 text-xs font-bold text-emerald-200">{skill}</span>)}{gaps.critical?.slice(0, 2).map((skill) => <span key={skill} className="rounded-md bg-red-400/10 px-2 py-1 text-xs font-bold text-red-200">Need: {skill}</span>)}</div></>}<div className="mt-5 flex flex-wrap gap-3"><button onClick={onAnalyze} className="text-sm font-extrabold text-orange-300">Analyze job</button><button onClick={onSave} className="text-sm font-extrabold text-slate-300">{saved ? "Unsave" : "Save job"}</button><a href={job.application?.officialUrl || job.applyUrl} target="_blank" rel="noreferrer" className="text-sm font-extrabold text-white">Apply on official site ↗</a></div></article>; }

function JobAnalysisModal({ analysis, loading, onClose }) { const job = analysis?.job; const match = analysis?.match; return <div className="fixed inset-0 z-[70] grid place-items-center bg-black/60 p-5"><section className="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-xl border border-white/10 bg-[#172033] p-6 text-white"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-extrabold uppercase tracking-widest text-orange-400">Job analysis</p><h2 className="mt-2 text-2xl font-black">{job?.title || "Analyzing role"}</h2><p className="mt-1 text-sm text-slate-300">{job?.company}</p></div><button onClick={onClose} className="text-slate-300">Close</button></div>{loading ? <p className="mt-8 text-sm text-slate-300">Comparing your profile, requirements and alumni paths…</p> : analysis ? <div className="mt-7 space-y-6"><section className="grid gap-4 sm:grid-cols-3"><Stat label="Profile match" value={match.overallScore != null ? `${match.overallScore}%` : "Unavailable"}/><Stat label="Eligibility" value={match.eligible ? "Eligible" : "Check requirements"}/><Stat label="Verification" value={job.verification?.status || "Pending"}/></section>{!match.eligible && <div className="rounded-lg border border-red-400/30 bg-red-400/10 p-4 text-sm text-red-100">{match.failedRequirements.join(" · ")}</div>}<SkillList title="You already have" items={match.matchedRequirements} tone="good"/><SkillList title="Critical gaps" items={match.gaps.critical} tone="critical"/><SkillList title="Recommended" items={match.gaps.recommended} tone="recommended"/><SkillList title="Nice to have" items={match.gaps.optional} tone="optional"/>{analysis.relevantAlumni?.length ? <section><p className="text-xs font-extrabold uppercase tracking-widest text-orange-400">Relevant Newbert alumni</p><div className="mt-3 grid gap-3 sm:grid-cols-3">{analysis.relevantAlumni.map((item) => <div key={item.alumni._id} className="rounded-lg border border-white/10 p-3"><p className="font-extrabold">{item.alumni.name}</p><p className="mt-1 text-xs text-slate-300">{item.alumni.company} · {item.match.overallScore}% profile match</p></div>)}</div></section> : null}<a href={`/resume-ai?jobId=${job._id}`} className="inline-flex rounded-lg bg-orange-500 px-4 py-3 text-sm font-extrabold text-slate-950">Optimize Resume For This Job</a></div> : null}</section></div>; }
function Stat({ label, value }) { return <div className="rounded-lg border border-white/10 bg-black/10 p-4"><p className="text-xs font-bold text-slate-400">{label}</p><p className="mt-1 font-extrabold">{value}</p></div>; }
function SkillList({ title, items = [], tone }) { if (!items.length) return null; const colors = { good: "text-emerald-200 bg-emerald-400/10", critical: "text-red-200 bg-red-400/10", recommended: "text-orange-200 bg-orange-400/10", optional: "text-slate-200 bg-white/10" }; return <section><p className="text-xs font-extrabold uppercase tracking-widest text-slate-400">{title}</p><div className="mt-2 flex flex-wrap gap-2">{items.map((item) => <span key={item} className={`rounded-md px-2.5 py-1 text-xs font-bold ${colors[tone]}`}>{item}</span>)}</div></section>; }
