import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import useAuth from "../hook/useAuth";
import { getLeaderboard } from "../Services/jobService";

export default function LeaderBoard() {
  const { profile, isAuthenticated } = useAuth();
  const hasCollege = Boolean(profile?.collegeId);
  const [scope, setScope] = useState(() => hasCollege ? "college" : "global");
  const [search, setSearch] = useState("");
  const [data, setData] = useState({ users: [], currentUser: null });
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  useEffect(() => { if (hasCollege) setScope("college"); else if (scope === "college") setScope("global"); }, [hasCollege]);
  useEffect(() => { let active = true; if (!isAuthenticated) { setLoading(false); return undefined; } setLoading(true); const timer = setTimeout(() => getLeaderboard({ scope, search: search || undefined }).then((result) => { if (active) { setData(result); setError(""); } }).catch((requestError) => { if (active) setError(requestError.response?.data?.message || "Unable to load leaderboard."); }).finally(() => { if (active) setLoading(false); }), 200); return () => { active = false; clearTimeout(timer); }; }, [isAuthenticated, scope, search]);
  if (!isAuthenticated) return <main className="grid min-h-screen place-items-center bg-[#111827] px-5 text-center text-white"><div><h1 className="text-3xl font-black">Leaderboard</h1><p className="mt-3 text-slate-300">Sign in to compare your real Newbert activity.</p><Link to="/signin" className="mt-6 inline-flex rounded-lg bg-orange-500 px-4 py-3 font-extrabold text-slate-950">Sign in</Link></div></main>;
  const me = data.currentUser;
  return <main className="min-h-screen bg-[#111827] px-5 py-12 text-white md:py-16"><div className="mx-auto max-w-5xl"><header><p className="text-xs font-extrabold uppercase tracking-[.2em] text-orange-400">Leaderboard</p><h1 className="mt-3 text-3xl font-black md:text-5xl">Compete with students who are actually preparing.</h1></header><div className="mt-8 flex flex-wrap gap-2">{[["college", "My College"], ["global", "Global"]].map(([value, label]) => <button key={value} disabled={value === "college" && !hasCollege} onClick={() => setScope(value)} className={`rounded-lg px-4 py-2.5 text-sm font-extrabold disabled:cursor-not-allowed disabled:opacity-40 ${scope === value ? "bg-orange-500 text-slate-950" : "border border-white/15 text-slate-200"}`}>{label}</button>)}</div>{!hasCollege && <p className="mt-4 text-sm text-orange-200">Complete your college profile to unlock My College ranking.</p>}{scope === "college" && data.college?.name && <p className="mt-4 font-bold text-slate-300">{data.college.name}</p>}{me && <section className="mt-6 border-y border-white/10 py-5"><p className="text-xl font-black">You are #{me.rank} {scope === "college" ? "in your college" : "globally"}</p><p className="mt-1 text-sm text-slate-300">{me.rank === 1 ? "You are leading this board." : `${me.gapToNext} points to reach #${me.rank - 1}`}</p></section>}<input value={search} onChange={(event) => setSearch(event.target.value)} className="mt-6 w-full rounded-lg border border-white/10 bg-[#172033] px-4 py-3 text-sm text-white outline-none focus:border-orange-400 sm:max-w-sm" placeholder="Search student"/>{error && <p className="mt-5 text-red-300">{error}</p>}{loading ? <div className="mt-6 h-40 animate-pulse rounded-xl bg-white/10"/> : <section className="mt-6 space-y-3">{data.users.map((entry) => <Entry key={entry.userId} entry={entry} mine={entry.userId === profile?.userId} scope={scope}/>)}{!data.users.length && <div className="rounded-xl border border-dashed border-white/15 p-10 text-center text-slate-300">No leaderboard activity yet.</div>}</section>}</div></main>;
}

function Entry({ entry, mine, scope }) { const destination = mine ? "/profile" : `/profile/${entry.userId}`; return <article className={`rounded-xl border bg-[#172033] p-5 ${mine ? "border-orange-400" : "border-white/10"}`}><div className="flex flex-col gap-5 sm:flex-row sm:items-center"><Link to={destination} state={{ fromLeaderboard: scope }} className="flex min-w-0 flex-1 items-center gap-4"><span className="w-9 text-xl font-black text-orange-300">#{entry.rank}</span><div className="grid h-12 w-12 shrink-0 place-items-center overflow-hidden rounded-full bg-orange-500 font-black text-slate-950">{entry.avatar ? <img src={entry.avatar} alt="" className="h-full w-full object-cover"/> : entry.name.slice(0, 1)}</div><div className="min-w-0"><h2 className="truncate text-lg font-black">{mine ? `${entry.name} · You` : entry.name}</h2><p className="truncate text-sm text-slate-400">{entry.college || "College not listed"}{entry.branch ? ` · ${entry.branch}` : ""}</p></div></Link><div className="grid grid-cols-2 gap-4 text-sm sm:grid-cols-4"><Metric label="Score" value={entry.score}/><Metric label="LeetCode" value={entry.leetcode.connected ? `${entry.leetcode.totalSolved} total · +${entry.leetcode.today} submissions today` : "Not connected"}/><Metric label="GitHub" value={entry.github.connected ? `${entry.github.totalContributions} total · +${entry.github.today} today` : "Not connected"}/><Metric label="Streak" value={`${entry.streak} days`}/></div></div></article>; }
function Metric({ label, value }) { return <div><p className="text-xs font-bold text-slate-500">{label}</p><p className="mt-1 font-extrabold text-slate-100">{value}</p></div>; }
