import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import useAuth from "../hook/useAuth";
import { getLeaderboard } from "../Services/jobService";
import API from "../Services/api";

export default function LeaderBoard() {
  const { profile, isAuthenticated, refreshProfile } = useAuth();
  const [scope, setScope] = useState("college");
  const [search, setSearch] = useState("");
  const [data, setData] = useState({ overall: { top: [], currentUser: null }, streak: { users: [] }, leetcode: { users: [] }, github: { users: [] } });
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [refreshing, setRefreshing] = useState(false); const [refreshKey, setRefreshKey] = useState(0);
  const hasCollege = Boolean(profile?.collegeId || data.resolvedCollege?.id);
  useEffect(() => { let active = true; if (!isAuthenticated) { setLoading(false); return undefined; } setLoading(true); const timer = setTimeout(() => getLeaderboard({ scope, search: search || undefined }).then((result) => { if (!active) return; if (result.needsCollege && scope === "college") { setScope("global"); return; } setData(result); setError(""); }).catch((requestError) => { if (active) setError(requestError.response?.data?.message || "Leaderboard API is temporarily unavailable."); }).finally(() => { if (active) setLoading(false); }), 200); return () => { active = false; clearTimeout(timer); }; }, [isAuthenticated, scope, search, refreshKey]);
  const refreshStats = async () => { setRefreshing(true); setError(""); try { await API.post("/profiles/sync", {}); await refreshProfile(); setRefreshKey((value) => value + 1); } catch (requestError) { setError(requestError.response?.data?.message || "Unable to refresh your stats."); } finally { setRefreshing(false); } };
  if (!isAuthenticated) return <main className="grid min-h-screen place-items-center bg-[#111827] px-5 text-center text-white"><div><h1 className="text-3xl font-black">Leaderboard</h1><p className="mt-3 text-slate-300">Sign in to compare your real Newbert activity.</p><Link to="/signin" className="mt-6 inline-flex rounded-lg bg-orange-500 px-4 py-3 font-extrabold text-slate-950">Sign in</Link></div></main>;
  const me = data.overall?.currentUser;
  return <main className="min-h-screen bg-[#111827] px-5 py-12 text-white md:py-16"><div className="mx-auto max-w-6xl"><header><p className="text-xs font-extrabold uppercase tracking-[.2em] text-orange-400">Leaderboard</p><h1 className="mt-3 text-3xl font-black md:text-5xl">See who's leading Newbert today.</h1><div className="mt-7 flex flex-wrap gap-2">{[["college","My College"],["global","Global"]].map(([value,label])=><button key={value} disabled={value==="college"&&!hasCollege&&!loading} onClick={()=>setScope(value)} className={`rounded-lg px-4 py-2.5 text-sm font-extrabold disabled:opacity-40 ${scope===value?"bg-orange-500 text-slate-950":"border border-white/15 text-slate-200"}`}>{label}</button>)}<button onClick={refreshStats} disabled={refreshing} className="rounded-lg border border-white/15 px-4 py-2.5 text-sm font-extrabold text-slate-200 disabled:opacity-50">{refreshing?"Refreshing...":"Refresh my stats"}</button></div>{scope==="college"&&data.college?.name&&<p className="mt-4 font-bold text-slate-300">{data.college.name}</p>}{!hasCollege&&!loading&&<p className="mt-4 text-sm text-orange-200">Complete your college profile to unlock My College ranking.</p>}</header>{me&&<section className="mt-7 grid gap-4 border-y border-white/10 py-5 sm:grid-cols-3"><Stat label="Your Overall Rank" value={`#${me.rank}`}/><Stat label="Current Streak" value={`${me.streak.current} days`}/><Stat label="Next Rank" value={me.rank===1?"Leading this board":`${me.gapToNext} points to #${me.rank-1}`}/></section>}<input value={search} onChange={(event)=>setSearch(event.target.value)} placeholder="Search student" className="mt-6 w-full rounded-lg border border-white/10 bg-[#172033] px-4 py-3 text-sm outline-none focus:border-orange-400 sm:max-w-sm"/>{error&&<p className="mt-5 rounded-lg border border-red-400/30 bg-red-400/10 p-4 text-sm text-red-200">{error}</p>}{loading?<Skeletons/>:<><Podium users={data.overall?.top||[]} mineId={profile?.userId}/><Board title="Top Streak Maintainers" subtitle="Consistency across placement preparation." data={data.streak} mineId={profile?.userId} scope={scope} metric={(entry)=>`${entry.streak.current} day streak · ${entry.overallScore} pts`}/><div className="grid gap-6 lg:grid-cols-2"><Board title="Top LeetCode Solvers" subtitle="Stored LeetCode activity from connected profiles." data={data.leetcode} mineId={profile?.userId} scope={scope} metric={(entry)=>`${entry.leetcode.totalSolved} total · +${entry.leetcode.today} submissions today · ${entry.leetcode.last7Days} in 7 days`}/><Board title="Top GitHub Contributors" subtitle="Contribution-calendar activity from connected GitHub profiles." data={data.github} mineId={profile?.userId} scope={scope} metric={(entry)=>`${entry.github.totalContributions} total · +${entry.github.today} today · ${entry.github.last7Days} in 7 days`}/></div></>}</div></main>;
}

function Podium({users,mineId}){if(!users.length)return null;return <section className="mt-8"><p className="text-xs font-extrabold uppercase tracking-widest text-orange-400">Top Newbert Performers</p><div className="mt-4 grid gap-3 sm:grid-cols-3">{users.map((entry)=><Link key={entry.userId} to={entry.userId===mineId?"/profile":`/profile/${entry.userId}`} className={`rounded-xl border bg-[#172033] p-5 ${entry.userId===mineId?"border-orange-400":"border-white/10"}`}><p className="text-2xl font-black text-orange-300">#{entry.rank}</p><p className="mt-3 text-lg font-black">{entry.name}{entry.userId===mineId?" · You":""}</p><p className="mt-1 text-sm text-slate-400">{entry.college.name||"College not listed"}</p><p className="mt-4 font-extrabold">{entry.overallScore} pts</p></Link>)}</div></section>}
function Board({title,subtitle,data={},mineId,scope,metric}){const mine=data.currentUser;return <section className="mt-8 rounded-xl border border-white/10 bg-[#172033] p-5"><div className="border-b border-white/10 pb-4"><h2 className="text-xl font-black">{title}</h2><p className="mt-1 text-sm text-slate-400">{subtitle}</p>{mine&&<p className="mt-3 text-sm font-bold text-orange-200">Your Rank: #{mine.rank} · {metric(mine)}</p>}</div><div className="mt-3 space-y-1">{(data.users||[]).map((entry)=><Link key={entry.userId} to={entry.userId===mineId?"/profile":`/profile/${entry.userId}`} state={{fromLeaderboard:scope}} className={`flex items-center gap-3 rounded-lg border px-3 py-3 ${entry.userId===mineId?"border-orange-400 bg-orange-400/5":"border-transparent hover:border-white/10"}`}><span className="w-7 font-black text-orange-300">#{entry.rank}</span><div className="grid h-9 w-9 shrink-0 place-items-center overflow-hidden rounded-full bg-orange-500 font-black text-slate-950">{entry.avatar?<img src={entry.avatar} alt="" className="h-full w-full object-cover"/>:entry.name.slice(0,1)}</div><div className="min-w-0 flex-1"><p className="truncate font-extrabold">{entry.userId===mineId?`${entry.name} · You`:entry.name}</p><p className="truncate text-xs text-slate-400">{entry.college.name}{entry.branch?` · ${entry.branch}`:""}</p></div><p className="max-w-[45%] text-right text-xs font-bold text-slate-200">{metric(entry)}</p></Link>)}{!(data.users||[]).length&&<p className="py-6 text-center text-sm text-slate-400">No connected users in this scope yet.</p>}</div></section>}
function Stat({label,value}){return <div><p className="text-xs font-bold uppercase tracking-wider text-slate-500">{label}</p><p className="mt-2 text-xl font-black text-orange-300">{value}</p></div>}
function Skeletons(){return <div className="mt-8 space-y-6">{[1,2,3,4].map((item)=><div key={item} className="h-36 animate-pulse rounded-xl bg-white/10"/>)}</div>}
