import { useCallback, useEffect, useState } from "react";
import { Link } from "react-router-dom";
import useAuth from "../hook/useAuth";
import { cancelMentorshipRequest, getMyMentorshipRequests, getReceivedMentorshipRequests, respondToMentorshipRequest } from "../Services/alumniService";

export default function Mentorship() {
  const { isAuthenticated } = useAuth();
  const [state, setState] = useState({ loading: true, mine: [], received: [], alumniProfile: false, error: "" });
  const load = useCallback(async (quiet = false) => {
    if (!isAuthenticated) { setState((current) => ({ ...current, loading: false })); return; }
    if (!quiet) setState((current) => ({ ...current, loading: true, error: "" }));
    try {
      const [mine, received] = await Promise.all([getMyMentorshipRequests(), getReceivedMentorshipRequests()]);
      setState({ loading: false, mine: mine.requests || [], received: received.requests || [], alumniProfile: Boolean(received.alumniProfile), error: "" });
    } catch (error) { setState((current) => ({ ...current, loading: false, error: error.response?.data?.message || "Mentorship requests could not be loaded." })); }
  }, [isAuthenticated]);
  useEffect(() => { load(); const timer = isAuthenticated ? setInterval(() => load(true), 15000) : null; return () => { if (timer) clearInterval(timer); }; }, [isAuthenticated, load]);
  if (!isAuthenticated) return <main className="mx-auto grid min-h-[70vh] max-w-xl place-items-center px-5 text-center"><div><h1 className="text-3xl font-black text-slate-950">Mentorship</h1><p className="mt-3 text-slate-600">Sign in to request guidance and follow every response inside Newbert.</p><Link to="/" className="mt-6 inline-flex rounded-lg bg-orange-500 px-5 py-3 font-extrabold text-slate-950">Sign in</Link></div></main>;
  return <main className="mx-auto max-w-6xl px-5 py-12"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-extrabold uppercase tracking-widest text-orange-600">In-app mentorship</p><h1 className="mt-2 text-3xl font-black text-slate-950">Mentorship requests</h1><p className="mt-2 text-sm text-slate-600">Status updates stay inside Newbert. This page refreshes automatically.</p></div><button onClick={() => load()} className="rounded-lg border border-slate-300 px-4 py-2 text-sm font-extrabold text-slate-700">Refresh</button></header>
    {state.error && <p className="mt-5 rounded-lg border border-red-200 bg-red-50 p-4 text-sm font-bold text-red-700">{state.error}</p>}
    {state.loading ? <Skeleton/> : <div className="mt-8 grid gap-8 lg:grid-cols-2"><RequestSection title="My Mentorship Requests" empty="You have not requested mentorship yet.">{state.mine.map((request) => <StudentRequest key={request._id} request={request} onChanged={load}/>)}</RequestSection>{state.alumniProfile && <RequestSection title="Requests Sent To Me" empty="No students have requested mentorship yet.">{state.received.map((request) => <ReceivedRequest key={request._id} request={request} onChanged={load}/>)}</RequestSection>}</div>}
  </main>;
}

function RequestSection({ title, empty, children }) { const items = Array.isArray(children) ? children : [children].filter(Boolean); return <section><h2 className="text-xl font-black text-slate-950">{title}</h2><div className="mt-4 space-y-3">{items.length ? items : <div className="rounded-xl border border-slate-200 bg-white p-6 text-sm text-slate-500">{empty}</div>}</div></section>; }
function StudentRequest({ request, onChanged }) { const alumni = request.alumniId || {}; const cancellable = ["requested", "accepted", "reschedule_requested"].includes(request.status); const cancel = async () => { await cancelMentorshipRequest(request._id); onChanged(); }; return <article className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="font-black text-slate-950">{alumni.name || "Alumni mentor"}</p><p className="mt-1 text-xs text-slate-500">{alumni.college || "College not listed"}</p></div><Status status={request.status} label={request.statusLabel}/></div><p className="mt-4 text-sm font-bold text-slate-800">{labelTopic(request.topicCategory)}</p><p className="mt-1 text-sm text-slate-600">{formatDate(request.confirmedDateTime || request.requestedDateTime)} · {request.durationMinutes} minutes</p>{request.alumniResponseNote && <p className="mt-3 rounded-lg bg-orange-50 p-3 text-sm text-orange-950">{request.alumniResponseNote}</p>}{cancellable && <button onClick={cancel} className="mt-4 text-xs font-extrabold text-red-700">Cancel request</button>}</article>; }
function ReceivedRequest({ request, onChanged }) { const [note, setNote] = useState(""); const [date, setDate] = useState(""); const [saving, setSaving] = useState(false); const act = async (status) => { setSaving(true); try { await respondToMentorshipRequest(request._id, { status, alumniResponseNote: note, ...(status === "reschedule_requested" && { confirmedDateTime: date }) }); onChanged(); } finally { setSaving(false); } }; const actionable = ["requested", "reschedule_requested", "accepted"].includes(request.status); return <article className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="font-black text-slate-950">{request.studentId?.name || "Student"}</p><p className="mt-1 text-xs text-slate-500">{labelTopic(request.topicCategory)}</p></div><Status status={request.status} label={request.statusLabel}/></div><p className="mt-4 text-sm leading-6 text-slate-700">{request.topicDetails}</p><p className="mt-3 text-xs font-bold text-slate-500">Requested: {formatDate(request.requestedDateTime)} · {request.durationMinutes} minutes</p>{actionable && <div className="mt-4 border-t border-slate-100 pt-4"><textarea value={note} onChange={(event) => setNote(event.target.value)} rows="2" placeholder="Optional response note" className="control w-full resize-none"/><label className="mt-3 block text-xs font-bold text-slate-600">New time for reschedule<input type="datetime-local" value={date} onChange={(event) => setDate(event.target.value)} className="control mt-1 w-full"/></label><div className="mt-3 flex flex-wrap gap-2">{request.status !== "accepted" && <button disabled={saving} onClick={() => act("accepted")} className="rounded-md bg-orange-500 px-3 py-2 text-xs font-extrabold text-slate-950">Accept</button>}<button disabled={saving || !date} onClick={() => act("reschedule_requested")} className="rounded-md border border-slate-300 px-3 py-2 text-xs font-extrabold text-slate-700">Request reschedule</button>{request.status !== "accepted" && <button disabled={saving} onClick={() => act("rejected")} className="rounded-md border border-red-200 px-3 py-2 text-xs font-extrabold text-red-700">Reject</button>}{request.status === "accepted" && <button disabled={saving} onClick={() => act("completed")} className="rounded-md border border-emerald-300 px-3 py-2 text-xs font-extrabold text-emerald-700">Mark completed</button>}</div></div>}</article>; }
function Status({ status, label }) { const colors = status === "accepted" || status === "completed" ? "bg-emerald-50 text-emerald-800" : status === "rejected" || status === "cancelled" ? "bg-red-50 text-red-700" : "bg-orange-50 text-orange-800"; return <span className={`rounded-full px-2.5 py-1 text-[11px] font-extrabold ${colors}`}>{label || status}</span>; }
function labelTopic(value) { return String(value || "Mentorship").replaceAll("-", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function formatDate(value) { return value ? new Date(value).toLocaleString() : "Time not confirmed"; }
function Skeleton() { return <div className="mt-8 grid gap-8 lg:grid-cols-2">{[1, 2].map((column) => <div key={column} className="space-y-3">{[1, 2, 3].map((item) => <div key={item} className="h-36 animate-pulse rounded-xl bg-slate-200"/>)}</div>)}</div>; }

