import { useState } from "react";
import { Link, Navigate, useParams } from "react-router-dom";

const branches = {
  electrical: { label: "Electrical Engineering", code: "EE", description: "Circuit theory, machines, electronics, and signals for AKTU electrical students.", semesters: [
    { id: "sem1", label: "1st Year · Sem 1", subjects: [{ id: "math1", name: "Engineering Mathematics I", units: ["Differential Calculus", "Integral Calculus", "Matrices", "Vector Calculus", "Differential Equations"] }, { id: "physics", name: "Engineering Physics", units: ["Wave Optics", "Laser and Fiber Optics", "Quantum Mechanics", "Semiconductor Physics", "Modern Physics"] }, { id: "bee", name: "Basic Electrical Engineering", units: ["DC Circuits", "AC Fundamentals", "Transformers", "Electrical Machines", "Power Measurement"] }] },
    { id: "sem3", label: "2nd Year · Sem 3", subjects: [{ id: "network", name: "Network Analysis and Synthesis", units: ["Circuit Laws", "Network Theorems", "Transient Analysis", "Two Port Networks", "Network Functions"] }, { id: "electronics", name: "Electronic Devices", units: ["Diodes", "BJT", "FET", "Amplifiers", "Power Supplies"] }, { id: "signals", name: "Signals and Systems", units: ["Signal Classification", "LTI Systems", "Fourier Series", "Fourier Transform", "Laplace Transform"] }] },
  ] },
  civil: { label: "Civil Engineering", code: "CE", description: "Surveying, structures, materials, and core construction concepts for AKTU civil students.", semesters: [
    { id: "sem1", label: "1st Year · Sem 1", subjects: [{ id: "math1", name: "Engineering Mathematics I", units: ["Differential Calculus", "Integral Calculus", "Matrices", "Vector Calculus", "Differential Equations"] }, { id: "physics", name: "Engineering Physics", units: ["Wave Optics", "Laser and Fiber Optics", "Quantum Mechanics", "Semiconductor Physics", "Modern Physics"] }, { id: "environment", name: "Environment and Ecology", units: ["Ecosystems", "Natural Resources", "Pollution", "Sustainable Development", "Environmental Impact"] }] },
    { id: "sem3", label: "2nd Year · Sem 3", subjects: [{ id: "survey", name: "Surveying", units: ["Chain Surveying", "Compass Surveying", "Theodolite", "Tacheometry", "Curves"] }, { id: "mechanics", name: "Engineering Mechanics", units: ["Forces", "Friction", "Centroid", "Trusses", "Dynamics"] }, { id: "materials", name: "Building Materials", units: ["Stones and Bricks", "Cement", "Concrete", "Timber", "Steel"] }] },
  ] },
  "information-technology": { label: "Information Technology", code: "IT", description: "Programming, data structures, databases, and systems for AKTU IT students.", semesters: [
    { id: "sem1", label: "1st Year · Sem 1", subjects: [{ id: "math1", name: "Engineering Mathematics I", units: ["Differential Calculus", "Integral Calculus", "Matrices", "Vector Calculus", "Differential Equations"] }, { id: "programming", name: "Programming for Problem Solving", units: ["C Fundamentals", "Control Flow", "Arrays and Strings", "Functions", "Pointers and Structures"] }, { id: "physics", name: "Engineering Physics", units: ["Wave Optics", "Laser and Fiber Optics", "Quantum Mechanics", "Semiconductor Physics", "Modern Physics"] }] },
    { id: "sem3", label: "2nd Year · Sem 3", subjects: [{ id: "dsa", name: "Data Structures", units: ["Arrays and Linked Lists", "Stacks and Queues", "Trees", "Graphs", "Sorting and Searching"] }, { id: "dbms", name: "Database Management Systems", units: ["ER Model", "Relational Algebra", "Normalization", "SQL", "Transactions"] }, { id: "oops", name: "Object Oriented Programming", units: ["Classes and Objects", "Inheritance", "Polymorphism", "Exception Handling", "File Handling"] }] },
  ] },
};

const youtubeLink = (branch, subject, unit) => `https://www.youtube.com/results?search_query=${encodeURIComponent(`Newbert AKTU ${branch.code} ${subject} ${unit}`)}`;

export default function Notes() {
  return <main className="notes-page min-h-screen bg-[#171918] px-5 py-12 text-white md:py-16"><div className="mx-auto max-w-6xl"><header className="border-b border-white/10 pb-9"><p className="text-xs font-extrabold uppercase tracking-[.2em] text-orange-400">Newbert learning hub</p><h1 className="mt-4 text-3xl font-extrabold md:text-5xl">Choose your AKTU branch.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">Open your branch to study semester-wise subjects, five-unit notes, revision prompts, and Newbert YouTube lecture links.</p></header><section className="mt-8 grid gap-4 md:grid-cols-3">{Object.entries(branches).map(([id, branch]) => <Link key={id} to={`/notes/${id}`} className="group border border-white/10 bg-[#20231f] p-6 transition hover:border-orange-400 hover:bg-orange-400/5"><p className="font-mono text-xs font-bold text-orange-300">{branch.code}</p><h2 className="mt-4 text-xl font-extrabold">{branch.label}</h2><p className="mt-3 text-sm leading-6 text-slate-400">{branch.description}</p><div className="mt-6 flex items-center justify-between border-t border-white/10 pt-4 text-xs font-bold"><span className="text-slate-500">{branch.semesters.length} semesters ready</span><span className="text-orange-300 group-hover:translate-x-1 transition">Open branch</span></div></Link>)}</section><div className="mt-8 border-l-2 border-orange-400 bg-orange-400/5 p-5"><p className="text-sm font-extrabold text-orange-200">Content team workflow</p><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">Every unit already has a YouTube destination. Replace the topic-search links in this page with each published Newbert video URL when your lectures go live.</p></div></div></main>;
}

export function BranchNotes() {
  const { branchId } = useParams();
  const branch = branches[branchId];
  const [semesterId, setSemesterId] = useState(branch?.semesters[0].id);
  const [subjectId, setSubjectId] = useState(branch?.semesters[0].subjects[0].id);
  const [activeUnit, setActiveUnit] = useState(null);
  const [completed, setCompleted] = useState([]);
  const [saved, setSaved] = useState([]);
  if (!branch) return <Navigate to="/notes" replace />;
  const semester = branch.semesters.find((item) => item.id === semesterId) || branch.semesters[0];
  const subject = semester.subjects.find((item) => item.id === subjectId) || semester.subjects[0];
  const unit = activeUnit || subject.units[0];
  const key = `${branchId}-${semester.id}-${subject.id}-${unit}`;
  const completedCount = subject.units.filter((item) => completed.includes(`${branchId}-${semester.id}-${subject.id}-${item}`)).length;
  const progress = Math.round((completedCount / subject.units.length) * 100);
  const detail = { summary: `${unit} for ${subject.name}: concise AKTU notes, examples, revision points, and a lecture linked from the Newbert YouTube channel.`, question: `Write a short AKTU answer on ${unit}. Include the definition, a labelled diagram or example, and one application.` };
  const changeSemester = (id) => { const next = branch.semesters.find((item) => item.id === id); setSemesterId(id); setSubjectId(next.subjects[0].id); setActiveUnit(null); };
  const changeSubject = (id) => { setSubjectId(id); setActiveUnit(null); };
  const toggle = (setItems) => setItems((current) => current.includes(key) ? current.filter((item) => item !== key) : [...current, key]);
  const download = () => { const text = `${subject.name}\n${unit}\n\n${detail.summary}\n\nRevision prompt:\n${detail.question}`; const url = URL.createObjectURL(new Blob([text], { type: "text/plain" })); const link = document.createElement("a"); link.href = url; link.download = `${branch.code}-${subject.id}-${unit.replace(/[^a-z0-9]/gi, "-").toLowerCase()}-notes.txt`; link.click(); URL.revokeObjectURL(url); };

  return <main className="notes-page min-h-screen bg-[#171918] px-5 py-12 text-white md:py-16"><div className="mx-auto max-w-6xl"><Link to="/notes" className="text-sm font-bold text-orange-300 hover:text-orange-200">Back to all branches</Link><header className="mt-7 border-b border-white/10 pb-8"><p className="font-mono text-xs font-bold text-orange-300">AKTU / {branch.code}</p><h1 className="mt-3 text-3xl font-extrabold md:text-5xl">{branch.label}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">{branch.description}</p></header>
    <section className="mt-7 border border-white/10 bg-[#20231f] p-5"><p className="text-sm font-extrabold">Semester</p><div className="mt-4 flex flex-wrap gap-2">{branch.semesters.map((item) => <button key={item.id} onClick={() => changeSemester(item.id)} className={`border px-3 py-2 text-xs font-bold ${semester.id === item.id ? "border-orange-400 bg-orange-500 text-[#171918]" : "border-white/10 text-slate-300 hover:border-orange-400"}`}>{item.label}</button>)}</div><div className="mt-6 grid gap-3 sm:grid-cols-3">{semester.subjects.map((item) => <button key={item.id} onClick={() => changeSubject(item.id)} className={`border p-4 text-left ${subject.id === item.id ? "border-orange-400 bg-orange-400/10" : "border-white/10 hover:border-orange-400/50"}`}><p className="text-sm font-extrabold">{item.name}</p><p className="mt-2 text-xs text-slate-500">5 units · notes + lectures</p></button>)}</div></section>
    <section className="mt-8 grid gap-6 lg:grid-cols-[.75fr_1.25fr]"><aside className="border border-white/10 bg-[#20231f] p-5"><div className="flex items-end justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[.14em] text-orange-400">{semester.label}</p><h2 className="mt-2 text-lg font-extrabold">{subject.name}</h2></div><p className="text-lg font-extrabold text-orange-300">{progress}%</p></div><div className="mt-4 h-1.5 bg-white/10"><div style={{ width: `${progress}%` }} className="h-full bg-orange-400 transition-all"/></div><div className="mt-5 space-y-2">{subject.units.map((item, index) => { const itemKey = `${branchId}-${semester.id}-${subject.id}-${item}`; return <button key={item} onClick={() => setActiveUnit(item)} className={`flex w-full items-center gap-3 border p-3 text-left ${unit === item ? "border-orange-400 bg-orange-400/10" : "border-white/10 hover:border-orange-400/50"}`}><span className={`grid h-6 w-6 place-items-center rounded-full text-[11px] font-extrabold ${completed.includes(itemKey) ? "bg-orange-400 text-[#171918]" : "bg-white/10 text-slate-400"}`}>{completed.includes(itemKey) ? "OK" : index + 1}</span><span className="flex-1 text-sm font-semibold">{item}</span><span className="text-[10px] font-bold text-slate-500">UNIT</span></button>; })}</div></aside>
      <article className="border border-white/10 bg-[#171918] p-6 md:p-8"><p className="text-xs font-extrabold uppercase tracking-[.16em] text-orange-400">Unit {subject.units.indexOf(unit) + 1} of 5 · {subject.name}</p><h2 className="mt-3 text-2xl font-extrabold md:text-3xl">{unit}</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-slate-400">{detail.summary}</p><div className="mt-7 grid gap-4 md:grid-cols-2"><div className="border border-white/10 bg-[#20231f] p-5"><p className="text-xs font-extrabold uppercase tracking-[.14em] text-orange-300">Notes pack</p><p className="mt-3 text-sm leading-6 text-slate-300">Concept sheet, solved examples, formula points, and revision prompt.</p><div className="mt-5 flex flex-wrap gap-2"><button onClick={download} className="bg-orange-500 px-3 py-2 text-xs font-extrabold text-[#171918] hover:bg-orange-400">Download notes</button><button onClick={() => toggle(setSaved)} className="border border-white/15 px-3 py-2 text-xs font-extrabold text-slate-300 hover:border-orange-400">{saved.includes(key) ? "Saved" : "Save unit"}</button></div></div><div className="border border-white/10 bg-[#20231f] p-5"><p className="text-xs font-extrabold uppercase tracking-[.14em] text-orange-300">Newbert YouTube lecture</p><p className="mt-3 text-sm leading-6 text-slate-300">Watch the lecture or attach your published Newbert video to this exact unit.</p><a href={youtubeLink(branch, subject.name, unit)} target="_blank" rel="noreferrer" className="mt-5 inline-block border border-orange-400/60 px-3 py-2 text-xs font-extrabold text-orange-300 hover:bg-orange-400 hover:text-[#171918]">Open YouTube lecture</a></div></div><div className="mt-5 border-l-2 border-orange-400 bg-orange-400/5 p-5"><p className="text-xs font-extrabold uppercase tracking-[.14em] text-orange-300">AKTU practice prompt</p><p className="mt-2 text-sm leading-6 text-slate-200">{detail.question}</p></div><button onClick={() => toggle(setCompleted)} className={`mt-6 px-4 py-3 text-sm font-extrabold ${completed.includes(key) ? "border border-orange-400 text-orange-300" : "bg-orange-500 text-[#171918] hover:bg-orange-400"}`}>{completed.includes(key) ? "Mark as not completed" : "Mark unit complete"}</button></article>
    </section></div></main>;
}
