import { useEffect, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { ExternalLink, Github, Globe } from "lucide-react";
import API from "../Services/api";
import useAuth from "../hook/useAuth";
import MomentumSection from "../profileComponents/MomentumSection";
import StreakLeaderboardPreview from "../profileComponents/StreakLeaderboardPreview";

export default function PublicProfile() {
  const { userId } = useParams();
  const navigate = useNavigate();
  const { profile: ownProfile } = useAuth();
  const [state, setState] = useState({ loading: true });
  useEffect(() => {
    if (ownProfile?.userId === userId) { navigate("/profile", { replace: true }); return undefined; }
    let active = true;
    API.get(`/profiles/${userId}/public`).then(({ data }) => { if (active) setState({ profile: data, loading: false }); }).catch((error) => { if (active) setState({ error: error.response?.data?.message || "Profile not found.", loading: false }); });
    return () => { active = false; };
  }, [userId, ownProfile?.userId, navigate]);
  if (state.loading) return <PublicProfileLoading/>;
  if (state.error) return <main className="min-h-screen bg-[#111827] p-10 text-white"><Link to="/leaderboard" className="text-orange-300">Back to Leaderboard</Link><p className="mt-8">{state.error}</p></main>;
  const p = state.profile;
  return <main className="min-h-screen bg-[#111827] px-5 py-12 text-white"><div className="mx-auto max-w-5xl"><Link to="/leaderboard" className="text-sm font-bold text-orange-300">Back to Leaderboard</Link><header className="mt-6 overflow-hidden border border-white/10 bg-[#172033]"><div className="h-32 bg-[#2c1c18] bg-cover bg-center" style={p.cover ? { backgroundImage: `url(${p.cover})` } : undefined}/><div className="px-6 pb-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end"><div className="-mt-10 grid h-24 w-24 shrink-0 place-items-center overflow-hidden rounded-full border-4 border-[#172033] bg-orange-500 text-2xl font-black text-slate-950">{p.avatar ? <img src={p.avatar} alt="" className="h-full w-full object-cover"/> : p.name?.slice(0, 1)}</div><div><h1 className="text-3xl font-black">{p.name}</h1>{!p.private && <p className="mt-1 text-slate-300">{p.college?.name || "College not listed"}{p.branch ? ` · ${p.branch}` : ""}</p>}</div></div>{p.activityPrivacy?.streakStatsVisible && p.leaderboard?.streakDays != null && <div className="mt-5 grid gap-3 sm:grid-cols-2"><Stat label="Current streak" value={`${p.leaderboard.streakDays} days`}/><Stat label="Longest streak" value={`${p.leaderboard.longestStreak} days`}/></div>}</div></header>{p.private ? <section className="mt-6 border border-white/10 bg-[#172033] p-8 text-center"><h2 className="text-xl font-black">{p.message || "This profile is private."}</h2><p className="mt-2 text-sm text-slate-400">Only the student's name and profile image are public.</p></section> : <PublicSections profile={p}/>}</div></main>;
}

function PublicSections({ profile: p }) {
  const links = [["LinkedIn", p.linkedin?.url], ["GitHub", p.github?.url], ["LeetCode", p.leetcode?.url]].filter(([, url]) => url);
  return <div className="mt-6 grid gap-6">{links.length > 0 && <Section title="Profile Links"><div className="flex flex-wrap gap-3">{links.map(([label, url]) => <a key={label} href={url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 border border-orange-400/40 bg-orange-400/10 px-3 py-2 text-sm font-extrabold text-orange-200 hover:border-orange-300 hover:text-orange-100">{label}<ExternalLink size={14}/></a>)}</div></Section>}<MomentumSection activityCalendar={p.activityCalendar || []} lastSyncedAt={p.leaderboard?.lastSyncedAt} currentStreak={p.leaderboard?.streakDays || 0} longestStreak={p.leaderboard?.longestStreak || 0} ownerName={p.name} heatmapVisible={p.activityPrivacy?.heatmapVisible !== false} streakStatsVisible={p.activityPrivacy?.streakStatsVisible !== false}/><StreakLeaderboardPreview snapshot={p.streakLeaderboard} ownerName={p.name}/>{p.projects?.featured?.length > 0 && <PublicFeaturedProjects projects={p.projects.featured}/>} {p.about && <Section title="About"><p className="text-sm leading-7 text-slate-300">{p.about.bio || "No bio added."}</p></Section>}{p.skills && <Section title="Skills"><div className="flex flex-wrap gap-2">{p.skills.length ? p.skills.map((skill) => <span key={skill} className="bg-orange-400/10 px-2.5 py-1.5 text-xs font-bold text-orange-100">{skill}</span>) : <p className="text-sm text-slate-400">No public skills listed.</p>}</div></Section>}<div className="grid gap-6 md:grid-cols-2">{p.github && <Section title="GitHub"><Integration connected={p.github.connected} lines={p.github.connected ? [`@${p.github.username}`, `${p.github.publicRepos} public repositories`, `${p.github.followers} followers`, p.github.metricAvailable ? `${p.github.activityToday} verified activities today${p.github.commitsToday ? ` · ${p.github.commitsToday} commits` : ""}` : "Refresh required for activity"] : []}/></Section>}{p.leetcode && <Section title="LeetCode"><Integration connected={p.leetcode.connected} lines={p.leetcode.connected ? [`@${p.leetcode.username}`, `${p.leetcode.totalSolved} total solved`, p.leetcode.metricAvailable ? `${p.leetcode.acceptedToday} accepted problems today` : "Refresh required for accepted-problem activity"] : []}/></Section>}</div><div className="grid gap-6 md:grid-cols-2">{p.education && <Section title="Education"><p className="font-bold">{p.education.graduationYear ? `Class of ${p.education.graduationYear}` : "Graduation year not listed"}</p>{p.education.cgpa != null && <p className="mt-2 text-sm text-slate-400">CGPA {p.education.cgpa}</p>}</Section>}{p.careerGoal && <Section title="Career Goal"><p className="font-bold">{p.careerGoal.role || "Not listed"}</p></Section>}</div></div>;
}
function PublicFeaturedProjects({ projects }) { return <Section title="Featured Projects"><div className="grid gap-4 md:grid-cols-3">{projects.slice(0, 3).map((project) => <article key={project.id} className="flex min-h-48 flex-col border border-white/10 bg-[#111a2b] p-4"><div className="flex-1"><p className="text-base font-black text-white">{project.name}</p>{project.evidenceLabel && <p className="mt-1 text-[11px] font-extrabold text-orange-300">{project.evidenceLabel}</p>}{project.description && <p className="mt-3 line-clamp-3 text-xs leading-5 text-slate-400">{project.description}</p>}<div className="mt-3 flex flex-wrap gap-1.5">{project.technologies.map((technology) => <span key={technology} className="bg-white/[.06] px-2 py-1 text-[11px] font-bold text-slate-200">{technology}</span>)}</div></div>{(project.repoUrl || project.liveUrl) && <div className="mt-4 flex gap-2 border-t border-white/10 pt-3">{project.repoUrl && <a href={project.repoUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1.5 text-xs font-extrabold text-orange-300"><Github size={14}/> GitHub</a>}{project.liveUrl && <a href={project.liveUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1.5 text-xs font-extrabold text-orange-300"><Globe size={14}/> Live demo</a>}</div>}</article>)}</div></Section>; }
function PublicProfileLoading() { return <main className="min-h-screen bg-[#111827] px-5 py-12"><div className="mx-auto max-w-5xl animate-pulse space-y-6"><div className="h-52 rounded-2xl bg-white/10"/><div className="h-96 rounded-2xl bg-white/10"/><div className="grid grid-cols-2 gap-4 sm:grid-cols-4">{[1, 2, 3, 4].map((item) => <div key={item} className="aspect-square rounded-xl bg-white/10"/>)}</div></div></main>; }
function Section({ title, children }) { return <section className="border border-white/10 bg-[#172033] p-6"><h2 className="text-xs font-extrabold uppercase tracking-widest text-orange-300">{title}</h2><div className="mt-4">{children}</div></section>; }
function Integration({ connected, lines }) { if (!connected) return <p className="text-sm text-slate-400">Not connected</p>; return <div className="space-y-1">{lines.map((line) => <p key={line} className="text-sm font-semibold text-slate-300">{line}</p>)}</div>; }
function Stat({ label, value }) { return <div className="border border-white/10 bg-black/10 p-4"><p className="text-xs font-bold text-slate-400">{label}</p><p className="mt-1 font-extrabold">{value}</p></div>; }
