import {useState} from 'react';
import {AnswerValue} from './AnswerFields';
import API from '../../Services/api';
export default function AlumniReview({session,onEdit,onPublish,onContinue,busy,preview}){
 const [confirmed,setConfirmed]=useState(false);const [audience,setAudience]=useState('public');
 return <section className="ac-review"><p className="ac-kicker">YOUR STORY, YOUR WORDS</p><h1>Make sure it feels like you.</h1><p>Review your answers and choose what juniors can see. Publishing is your approval to share; it does not mark your outcome as independently verified.</p>
 <details className="ac-preview"><summary>Preview what readers can see</summary><div className="ac-choices"><button aria-pressed={audience==='public'} onClick={()=>setAudience('public')}>Anyone</button><button aria-pressed={audience==='college'} onClick={()=>setAudience('college')}>Your college</button></div>{preview?.[audience]?<AnswerValue value={preview[audience]}/>:<p>Open review again to refresh this preview.</p>}</details>
 {session.missingRequired.length>0&&<p className="ac-alert">{session.missingRequired.length} required answers left. You can publish after completing them.</p>}
 {session.pendingExtraction&&<p className="ac-alert">Review the pending AI suggestion before publishing.</p>}
 {session.questions.map(q=><article key={q.id}><div className="ac-review-heading"><div><small>{q.section} {q.required?'· Required':''}</small><h3>{q.text}</h3></div><button className="ac-secondary" disabled={busy} onClick={()=>onEdit(q)}>Edit</button></div>{Object.hasOwn(session.answers,q.id)?<AnswerValue value={session.answers[q.id]}/>:<p>{session.skippedQuestions.includes(q.id)?'Skipped — optional':'Not answered yet'}</p>}</article>)}
 <label className="ac-consent"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/><span>I reviewed my story and privacy settings. Publish the information I chose to share on Newbert.</span></label>
 <div className="ac-actions"><button onClick={onContinue}>Continue conversation</button><button className="ac-primary" disabled={busy||!confirmed||!session.canPublish} onClick={onPublish}>{busy?'Publishing your story…':'Publish Alumni Story'}</button></div></section>;
}
export function PrivateEvidence(){const [file,setFile]=useState(null);const [source,setSource]=useState('OFFER_LETTER');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);async function upload(){if(!file)return;setBusy(true);setMessage('');try{if(file.size>2*1024*1024)throw new Error('Choose a file smaller than 2 MB.');const base64=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file);});const {data}=await API.post('/alumni-chat/documents',{source,filename:file.name,base64});setMessage(data.message);setFile(null);}catch(e){setMessage(e.response?.data?.message||e.message||'Evidence could not be saved.');}finally{setBusy(false);}}
 return <details className="ac-evidence"><summary>Optional private evidence</summary><p>Documents are stored privately for review. They never appear on the Alumni Wall. Verification remains pending until reviewed.</p><label>Evidence type<select value={source} onChange={e=>setSource(e.target.value)}>{['OFFER_LETTER','EMPLOYEE_ID','GATE_SCORECARD','COLLEGE_RECORD','COMPANY_EMAIL','OTHER'].map(v=><option key={v} value={v}>{v.replaceAll('_',' ')}</option>)}</select></label><input aria-label="Private verification document" type="file" accept="application/pdf,image/png,image/jpeg" onChange={e=>setFile(e.target.files?.[0]||null)}/><button className="ac-secondary" disabled={busy||!file} onClick={upload}>{busy?'Saving privately…':'Save private evidence'}</button>{message&&<p role="status">{message}</p>}</details>;
}
