import {useState} from 'react';
import CollegeAutocomplete from '../CollegeAutocomplete';
const collections=['skills','projects','internships','interview-rounds','timeline','resource-list','collection'];
const labelOf=option=>typeof option==='string'?option.replaceAll('_',' '):option.label;
const valueOf=option=>typeof option==='string'?option:option.value;
function formatAnswer(value){if(value===null||value===undefined)return 'Not shared';if(typeof value==='boolean')return value?'Yes':'No';if(Array.isArray(value))return value.map(formatAnswer).join(' · ');if(typeof value==='object')return Object.entries(value).map(([key,v])=>`${key.replace(/([A-Z])/g,' $1')}: ${formatAnswer(v)}`).join('\n');return String(value);}
export function AnswerValue({value}){if(Array.isArray(value))return <div className="ac-value-list">{value.map((v,i)=><div key={i}><AnswerValue value={v}/></div>)}</div>;if(value&&typeof value==='object')return <dl className="ac-facts">{Object.entries(value).filter(([,v])=>v!==null&&v!==undefined&&v!=='').map(([k,v])=><div key={k}><dt>{k.replace(/([A-Z])/g,' $1').replaceAll('_',' ')}</dt><dd><AnswerValue value={v}/></dd></div>)}</dl>;if(typeof value==='string'&&/^https?:\/\//.test(value))return <a href={value} target="_blank" rel="noreferrer">{value} ↗</a>;return <span>{formatAnswer(value)}</span>;}
export default function AnswerFields({field,value,onChange,privacyFields=[]}){
 if(collections.includes(field.type))return <CollectionInput field={field} value={Array.isArray(value)?value:[]} onChange={onChange}/>;
 if(field.type==='object')return <ObjectInput field={field} value={value||{}} onChange={onChange}/>;
 if(field.type==='college')return <CollegeAutocomplete value={value?.name||''} selectedCollege={value?.collegeId?value:null} onQueryChange={name=>onChange({name})} onSelect={college=>onChange({collegeId:college.collegeId||college._id,name:college.name})}/>;
 if(field.type==='privacy')return <PrivacyInput fields={privacyFields} value={value||{}} onChange={onChange}/>;
 if(field.type==='choice'||field.type==='yes-no'){const options=field.type==='yes-no'?[{value:true,label:'Yes'},{value:false,label:'No'}]:field.options;return <div className="ac-choices">{options.map(o=><button type="button" aria-pressed={value===valueOf(o)} key={String(valueOf(o))} onClick={()=>onChange(valueOf(o))}>{labelOf(o)}</button>)}</div>;}
 if(field.type==='multi-choice'||field.type==='platform-selector')return <MultiSelect field={field} value={Array.isArray(value)?value:[]} onChange={onChange}/>;
 if(field.type==='textarea')return <textarea aria-label={field.label||field.text} rows={4} maxLength={field.maxLength||3000} value={value||''} onChange={e=>onChange(e.target.value)} placeholder="Tell it in your own words…"/>;
 return <input aria-label={field.label||field.text} type={['number','year','rating'].includes(field.type)?'number':field.type==='date'?'date':field.type==='url'?'text':'text'} inputMode={['number','year','rating'].includes(field.type)?'decimal':field.type==='url'?'url':undefined} min={field.min} max={field.max} step="any" maxLength={field.maxLength||2048} value={value??''} placeholder={field.type==='url'?'https://…':undefined} onChange={e=>onChange(e.target.value)}/>;
}
function MultiSelect({field,value,onChange}){const [custom,setCustom]=useState('');const options=[...new Set([...(field.options||[]),...value])];return <div><div className="ac-choices">{options.map(o=><button type="button" key={o} aria-pressed={value.includes(o)} onClick={()=>onChange(value.includes(o)?value.filter(v=>v!==o):[...value,o])}>{o.replaceAll('_',' ')}</button>)}</div>{(field.custom||!field.options?.length)&&<div className="ac-inline"><input value={custom} aria-label={`Add ${field.label||'item'}`} onChange={e=>setCustom(e.target.value)} placeholder="Add your own, separated by commas"/><button type="button" onClick={()=>{onChange([...new Set([...value,...custom.split(',').map(v=>v.trim()).filter(Boolean)])]);setCustom('');}}>Add</button></div>}</div>;}
function CollectionInput({field,value,onChange}){
 const [editing,setEditing]=useState(null);const [draft,setDraft]=useState({});const [step,setStep]=useState(0);const [error,setError]=useState('');
 const fields=field.fields||[];const current=fields[step];
 const begin=index=>{setEditing(index);setDraft(index<value.length?value[index]:{});setStep(0);setError('');};
 function finish(){if(fields.some(f=>f.required&&(draft[f.id]===undefined||draft[f.id]===''||Array.isArray(draft[f.id])&&!draft[f.id].length))){setError('Complete the required details before keeping this entry.');return;}const items=[...value];items[editing]=draft;onChange(items);setEditing(null);setDraft({});}
 function next(){if(current.required&&(draft[current.id]===undefined||draft[current.id]===''||Array.isArray(draft[current.id])&&!draft[current.id].length)){setError('Add this detail before continuing.');return;}setError('');if(step<fields.length-1){setStep(step+1);return;}const items=[...value];items[editing]=draft;onChange(items);setEditing(null);setDraft({});}
 return <div className="ac-collection">{value.map((item,i)=><article key={i}><div><b>{item.name||item.company||item.title||item.platformLabel||`Entry ${i+1}`}</b><small>{item.role||item.description||item.duration}</small></div><button type="button" onClick={()=>begin(i)}>Edit entry {i+1}</button><button type="button" onClick={()=>onChange(value.filter((_,j)=>i!==j))} aria-label={`Remove entry ${i+1}`}>Remove</button></article>)}
 {editing===null?<button className="ac-secondary" type="button" onClick={()=>begin(value.length)}>+ Add {value.length?'another':'an entry'}</button>:<div className="ac-entry"><p className="ac-kicker">ENTRY {editing+1} · DETAIL {step+1} OF {fields.length}</p><h3>{current.label}{current.required?' *':''}</h3><AnswerFields key={`${editing}:${step}`} field={current} value={draft[current.id]} onChange={v=>setDraft({...draft,[current.id]:v})}/>{error&&<p role="alert">{error}</p>}<div className="ac-actions"><button type="button" onClick={()=>setEditing(null)}>Cancel entry</button>{step<fields.length-1&&<button type="button" onClick={finish}>Keep entry now</button>}{step>0&&<button type="button" onClick={()=>setStep(step-1)}>Previous detail</button>}<button className="ac-primary" type="button" onClick={next}>{step===fields.length-1?'Keep entry':'Next detail'}</button></div></div>}
 </div>;
}

function ObjectInput({field,value,onChange}){
 const fields=field.fields||[];const primary=fields.some(f=>f.required)?fields.filter(f=>f.required):fields.slice(0,3);const more=fields.filter(f=>!primary.includes(f));
 const render=items=><div className="ac-fields">{items.map(child=><label key={child.id}><span>{child.label}{child.required?' *':''}</span><AnswerFields field={child} value={value[child.id]} onChange={v=>onChange({...value,[child.id]:v})}/></label>)}</div>;
 return <div>{render(primary)}{more.length>0&&<details className="ac-more"><summary>More details (optional)</summary>{render(more)}</details>}</div>;
}

function PrivacyInput({fields,value,onChange}){
 const groups=[...new Set(fields.map(f=>f.key.split('.')[0]))];
 return <div className="ac-privacy"><p>Professional details start public. Salary and stipends start college only. Documents and contact information are never published. Open a section to adjust its fields.</p>{groups.map(group=>{const items=fields.filter(f=>f.key===group||f.key.startsWith(group+'.'));return <details key={group} className="ac-privacy-group"><summary>{group.replace(/([A-Z])/g,' $1').replace('practice:','Practice profile: ')} <small>{items.length} {items.length===1?'field':'fields'}</small></summary>{items.map(item=><label key={item.key}><span>{item.key===group?'Whole section':item.label.split(' / ').slice(1).join(' / ')}</span><select aria-label={`Visibility: ${item.key}`} value={value[item.key]||item.default} onChange={e=>onChange({...value,[item.key]:e.target.value})}><option value="PUBLIC">Public</option><option value="COLLEGE_ONLY">College only</option><option value="PRIVATE">Private</option></select></label>)}</details>})}</div>;
}
