import {useEffect,useState} from 'react';
import AnswerFields,{AnswerValue} from './AnswerFields';
function emptyValue(q){return ['object','privacy','college'].includes(q.type)?{}:['projects','internships','skills','interview-rounds','timeline','resource-list','collection','multi-choice','platform-selector'].includes(q.type)?[]:'';}
export default function QuestionRenderer({question,session,scope,privacyFields,onAnswer,onExtract,onConfirm,onSkip,onBack,onPracticeCheck,busy,returnToReview,audience='alumni'}){
 const q=question;const draftKey=`newbert:alumni-draft:${scope}:${q.id}`;
 const [value,setValue]=useState(()=>{try{const cached=JSON.parse(sessionStorage.getItem(draftKey)||'null');return cached?.version===session?.version?cached.value:session?.answers?.[q.id]??emptyValue(q);}catch{return session?.answers?.[q.id]??emptyValue(q);}});
 const [mode,setMode]=useState('details');const [raw,setRaw]=useState(session?.rawAnswers?.[q.id]&&typeof session.rawAnswers[q.id]==='string'?session.rawAnswers[q.id]:'');const [check,setCheck]=useState(null);const [checking,setChecking]=useState(false);
 const pending=session.pendingExtraction?.questionId===q.id?session.pendingExtraction:null;
 useEffect(()=>{try{sessionStorage.setItem(draftKey,JSON.stringify({version:session.version,value}));}catch{/* The server keeps submitted answers even if browser storage is unavailable. */}},[draftKey,session.version,value]);
 async function inspect(){setChecking(true);try{const {data}=await onPracticeCheck(q.id,value);setCheck(data);}catch(e){setCheck({message:e.response?.data?.message||'The link can still be saved without checking it.'});}finally{setChecking(false);}}
 async function submit(event){event.preventDefault();if(pending){await onConfirm(value);return;}await onAnswer(q.id,value);}
 return <section className="ac-conversation" aria-label={audience==='student'?'Student profile question':'Alumni interview question'}><div className="ac-bot"><span className="ac-bot-icon" aria-hidden="true">N</span><div><p className="ac-kicker">NEWBERT · {q.section}</p><h2 tabIndex={-1}>{q.text}</h2><p>{q.required?'Needed for your story':'Optional · share what feels useful'}</p></div></div>
 {pending?<div className="ac-extraction"><p className="ac-kicker">CHECK WHAT I UNDERSTOOD</p><p>This is a suggestion. Check every detail before keeping it.</p><AnswerValue value={pending.answer}/>{pending.estimatedFields?.length>0&&<p>Estimates: {pending.estimatedFields.join(', ')}</p>}<button type="button" className="ac-primary" disabled={busy} onClick={()=>onConfirm(pending.answer)}>Correct — keep these details</button><button type="button" className="ac-secondary" onClick={()=>{setValue(pending.answer);setMode('details');}}>Edit extracted details below</button></div>:null}
 {q.ai&&!pending&&<div className="ac-mode"><button type="button" aria-pressed={mode==='details'} onClick={()=>setMode('details')}>Enter details</button><button type="button" aria-pressed={mode==='natural'} onClick={()=>setMode('natural')}>Tell it in my words</button></div>}
 {mode==='natural'&&!pending?<div className="ac-natural"><textarea aria-label="Tell Newbert in your own words" rows={6} maxLength={6000} value={raw} onChange={e=>setRaw(e.target.value)} placeholder="For example: I joined as a frontend intern, worked on React dashboards, and received a PPO…"/><p>Only this answer is sent to Gemini when you choose Organise. You review the result before it is used.</p><button className="ac-primary" disabled={busy||!raw.trim()} onClick={()=>onExtract(q.id,raw)}>{busy?'Newbert is organising your answer…':'Organise my answer'}</button></div>:<form onSubmit={submit}><fieldset disabled={busy}><AnswerFields field={q} value={value} onChange={setValue} privacyFields={privacyFields}/>{['GITHUB','LEETCODE'].includes(q.platform)&&<div className="ac-profile-check"><button type="button" disabled={checking||!value?.profileUrl} onClick={inspect}>{checking?'Checking profile…':'Check current public metrics (optional)'}</button>{check&&<><p>{check.message}</p>{check.metrics&&<AnswerValue value={check.metrics}/>}</>}</div>}
 <div className="ac-actions"><button type="button" onClick={onBack} disabled={busy}>← Back</button>{!q.required&&<button type="button" onClick={()=>onSkip(q.id)}>Skip for now</button>}<button className="ac-primary" type="submit">{busy?'Saving your answer…':returnToReview?'Save & return to review':pending?'Confirm edited details':'Save & continue'} →</button></div></fieldset></form>}
 <p className="ac-save-hint">{audience==='guest'?'Submitted answers save to this browser’s private story key. Keep this browser to edit later.':'Submitted answers save to your account immediately. You can leave and come back.'}</p>
 </section>;
}
