const Session=require('../Models/AlumniChatSession');
const Alumni=require('../Models/Alumni');
const User=require('../Models/User');
const Profile=require('../Models/Profile');
const Document=require('../Models/AlumniVerificationDocument');
const engine=require('../services/alumniQuestionEngine');
const {initialSession,ownerSnapshot,buildPublication}=require('../services/alumniChatService');
const {findCollegeByIdentifier}=require('../services/collegeService');
const {extractAnswer}=require('../services/alumniAIService');
const {invalid,cleanText,normalizePractice}=require('../services/alumniChatValidation');
function fail(message,status){const e=new Error(message);e.status=status;throw e;}
const handle=fn=>async(req,res,next)=>{try{await fn(req,res);}catch(e){if(e.name==='VersionError'||e.code===11000)return res.status(409).json({message:'Your conversation changed in another tab. Reload the saved conversation and try again.'});next(e);}};
async function load(req,checkVersion=true){const s=await Session.findOne({userId:req.auth.id});if(!s)fail('Start your alumni story first.',404);if(s.publishLockUntil>new Date())fail('Your story is being published. Please wait a moment.',409);if(checkVersion&&req.body.version!==s.__v)fail('Your conversation changed in another tab. Reload your saved progress.',409);return s;}
async function save(session){session.lastActivityAt=new Date();for(const field of ['answers','rawAnswers','extractedAnswers','inactiveAnswers','prefill','pendingExtraction'])session.markModified(field);await session.save();}
async function normalizeCollege(q,value){if(q.id!=='college')return value;const c=await findCollegeByIdentifier(value?.collegeId||value?._id);if(!c)invalid('Choose a college from the suggestions.');return {name:c.name,collegeId:c.collegeId};}
exports.start=handle(async(req,res)=>{let s=await Session.findOne({userId:req.auth.id});if(!s){const [user,profile,alumni]=await Promise.all([User.findById(req.auth.id).lean(),Profile.findOne({userId:req.auth.id}).lean(),Alumni.findOne({userId:req.auth.id}).lean()]);if(!user)fail('Your account was not found.',401);try{s=await Session.create(initialSession(user,profile,alumni));}catch(e){if(e.code!==11000)throw e;s=await Session.findOne({userId:req.auth.id});}}res.json(ownerSnapshot(s));});
exports.session=handle(async(req,res)=>{const s=await Session.findOne({userId:req.auth.id});res.json(s?ownerSnapshot(s):{session:null});});
exports.prefill=handle(async(req,res)=>{const s=await load(req);if(req.body.use===true){for(const [id,v]of Object.entries(s.prefill||{})){const q=engine.relevantQuestions({...s.answers,...s.prefill}).find(q=>q.id===id);if(!q||Object.hasOwn(s.answers,id))continue;try{const value=await normalizeCollege(q,v);s.answers={...s.answers,[id]:engine.validatedAnswer(q,value)};s.rawAnswers={...s.rawAnswers,[id]:value};}catch{/* Invalid or outdated profile fields are asked again. */}}}s.prefill={};engine.reconcile(s);await save(s);res.json(ownerSnapshot(s));});
exports.answer=handle(async(req,res)=>{const s=await load(req);const id=req.params.questionId||req.body.questionId;const q=engine.questionFor(s,id);engine.answer(s,id,await normalizeCollege(q,req.body.value),req.body.rawAnswer);await save(s);res.json(ownerSnapshot(s));});
exports.skip=handle(async(req,res)=>{const s=await load(req);engine.skip(s,req.body.questionId);await save(s);res.json(ownerSnapshot(s));});
exports.back=handle(async(req,res)=>{const s=await load(req);engine.back(s);await save(s);res.json(ownerSnapshot(s));});
exports.review=handle(async(req,res)=>{const s=await load(req,false);res.json(ownerSnapshot(s,{preview:buildReview(s)}));});
function buildReview(s){const {redactStory,legacyFields}=require('../services/alumniStoryService');const privacy=s.answers.privacy||{};return {public:legacyFields(redactStory(s.answers,privacy,false)),college:legacyFields(redactStory(s.answers,privacy,true))};}
exports.extract=handle(async(req,res)=>{const s=await load(req);const q=engine.questionFor(s,req.body.questionId);if(!q.ai)invalid('This question uses direct answers.');const raw=cleanText(req.body.rawAnswer,6000);if(!raw)invalid('Write your answer first.');s.rawAnswers={...s.rawAnswers,[q.id]:raw};s.pendingExtraction=null;s.currentQuestionId=q.id;s.currentSection=q.section;await save(s);
 let extraction;try{extraction=await extractAnswer(q,raw);}catch{const fresh=await Session.findOne({userId:req.auth.id});return res.json(ownerSnapshot(fresh,{notice:'Your original answer is saved. AI could not organise it; enter the details below or continue with another question.'}));}
 // Optimistic concurrency prevents a late AI response overwriting a newer answer or account edit.
 s.pendingExtraction={questionId:q.id,rawAnswer:raw,...extraction};await save(s);res.json(ownerSnapshot(s));});
exports.confirm=handle(async(req,res)=>{const s=await load(req);const pending=s.pendingExtraction;if(!pending)invalid('There is no extraction to confirm.');const value=req.body.value??pending.answer;engine.answer(s,pending.questionId,value,pending.rawAnswer);s.extractedAnswers={...s.extractedAnswers,[pending.questionId]:{...pending,answer:s.answers[pending.questionId],confirmedAt:new Date()}};await save(s);res.json(ownerSnapshot(s));});
exports.publish=handle(async(req,res)=>{if(req.body.confirm!==true)invalid('Review your profile and confirm publication.');const s=await load(req);const college=await findCollegeByIdentifier(s.answers.college?.collegeId);const payload=buildPublication(s,college);s.publishLockUntil=new Date(Date.now()+30000);await save(s);try{const alumni=await Alumni.findOneAndUpdate({userId:req.auth.id},{$set:payload,$setOnInsert:{userId:req.auth.id}},{new:true,upsert:true,runValidators:true,setDefaultsOnInsert:true});s.publishedAlumniId=alumni._id;s.status='COMPLETED';s.completedAt=new Date();s.publishLockUntil=null;await save(s);res.json(ownerSnapshot(s));}catch(e){s.publishLockUntil=null;await save(s);throw e;}});
exports.restart=handle(async(req,res)=>{if(req.body.confirm!==true)invalid('Confirm restarting your draft. Your published story remains unchanged.');const s=await load(req);s.answers={};s.rawAnswers={};s.extractedAnswers={};s.inactiveAnswers={};s.history=[];s.skippedQuestions=[];s.pendingExtraction=null;s.startedAt=new Date();s.completedAt=null;engine.reconcile(s);await save(s);res.json(ownerSnapshot(s));});
exports.hide=handle(async(req,res)=>{if(req.body.confirm!==true)invalid('Confirm hiding your published story.');await Alumni.updateOne({userId:req.auth.id},{$set:{publicationStatus:'HIDDEN'}});res.json({message:'Your alumni story is hidden from the Alumni Wall.'});});
exports.inspectPractice=handle(async(req,res)=>{const s=await load(req,false);const q=engine.questionFor(s,req.body.questionId);if(!['GITHUB','LEETCODE'].includes(q.platform))invalid('Live information is available for GitHub and LeetCode.');const p=normalizePractice(q.platform,req.body.value);let metrics;try{if(q.platform==='LEETCODE'){const result=await require('../services/leetcodeService').getLeetcodeStats(p.username,[new Date().getFullYear()]);metrics={currentSolved:result.totalSolved};}else{const result=await require('../services/githubService').getGithubActivity(p.username,[new Date().getFullYear()],{skipRepoScan:true});metrics={publicRepositories:result.publicRepos??result.public_repos??null};}res.json({metrics,message:'These are current public metrics, not proof of identity or your selection-time counts.'});}catch{res.json({metrics:null,message:'We could not check this profile right now. You can still save the link.'});}});
exports.documents=handle(async(req,res)=>{const documents=await Document.find({userId:req.auth.id}).select('source filename mimeType size status createdAt').lean();res.json({documents});});
exports.upload=handle(async(req,res)=>{const allowed=['LINKEDIN','GITHUB','LEETCODE','COMPANY_EMAIL','OFFER_LETTER','EMPLOYEE_ID','GATE_SCORECARD','COLLEGE_RECORD','OTHER'];if(!allowed.includes(req.body.source))invalid('Choose an evidence type.');if(typeof req.body.base64!=='string'||req.body.base64.length>2800000||!/^[a-zA-Z0-9+/]*={0,2}$/.test(req.body.base64))invalid('Upload a PDF, PNG or JPEG smaller than 2 MB.');const data=Buffer.from(req.body.base64,'base64');const mime=data.subarray(0,5).toString()==='%PDF-'?'application/pdf':data.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]))?'image/png':data[0]===255&&data[1]===216&&data[2]===255?'image/jpeg':null;if(!mime||data.length>2*1024*1024)invalid('Upload a PDF, PNG or JPEG smaller than 2 MB.');if(await Document.countDocuments({userId:req.auth.id})>=10)invalid('You can keep up to 10 private evidence documents.');const filename=cleanText(req.body.filename||'evidence',120).replace(/[^\w. -]/g,'_');const doc=await Document.create({userId:req.auth.id,source:req.body.source,filename,mimeType:mime,size:data.length,data});res.status(201).json({document:{id:doc._id,source:doc.source,filename,status:doc.status,size:doc.size},message:'Private evidence saved for review. It is never included in public alumni responses.'});});
exports.download=handle(async(req,res)=>{const doc=await Document.findOne({_id:req.params.id,userId:req.auth.id}).select('+data');if(!doc)fail('Evidence not found.',404);res.set('Content-Type','application/octet-stream');res.set('X-Content-Type-Options','nosniff');res.set('Content-Disposition',`attachment; filename="${doc.filename.replace(/[^\w. -]/g,'_')}"`);res.set('Cache-Control','no-store');res.send(doc.data);});
