const {questions}=require('../config/alumniQuestions');
const {validate,normalizePractice,invalid}=require('./alumniChatValidation');
function matches(when,answers){if(!when)return true;if(when.any)return when.any.some(rule=>matches(rule,answers));const value=answers[when.field];if(value==null)return false;return when.values?when.values.includes(value):!when.not.includes(value);}
function relevantQuestions(answers={}){
  const result=[];
  for(const question of questions){if(!matches(question.when,answers))continue;result.push(question);if(question.id==='platforms')for(const platform of answers.platforms||[]){result.push({id:`practice:${platform}`,section:'Profiles',text:platform==='OTHER'?'Add any other platforms where you shared or practised your work.':`Add your ${platform.replaceAll('_',' ')} profile.`,type:platform==='OTHER'?'collection':'object',required:false,platform,fields:[...(platform==='OTHER'?[{id:'platformLabel',label:'Platform name',type:'text',required:true}]:[]),{id:'profileUrl',label:'Profile URL',type:'url',required:true},{id:'username',label:'Username (optional)',type:'text'}]});}}
  return result;
}
function isAnswered(session,q){return Object.hasOwn(session.answers||{},q.id)||(session.skippedQuestions||[]).includes(q.id);}
function state(session){const relevant=relevantQuestions(session.answers);const done=relevant.filter(q=>isAnswered(session,q));const missing=relevant.filter(q=>q.required&&!Object.hasOwn(session.answers||{},q.id));const sections=[...new Set(relevant.map(q=>q.section))].map(name=>({name,total:relevant.filter(q=>q.section===name).length,completed:done.filter(q=>q.section===name).length}));const current=relevant.find(q=>q.id===session.currentQuestionId)||relevant.find(q=>!isAnswered(session,q))||null;return {questions:relevant,currentQuestion:current,progress:Math.round(done.length/relevant.length*100),completed:done.length,total:relevant.length,missingRequired:missing.map(q=>q.id),sections,canPublish:!missing.length&&!session.pendingExtraction};}
function reconcile(session,preferred){const allowed=new Set(relevantQuestions(session.answers).map(q=>q.id));for(const id of Object.keys(session.answers)){if(!allowed.has(id)){session.inactiveAnswers={...session.inactiveAnswers,[id]:session.answers[id]};delete session.answers[id];}}
  session.skippedQuestions=(session.skippedQuestions||[]).filter(id=>allowed.has(id));
  if(session.pendingExtraction&&!allowed.has(session.pendingExtraction.questionId))session.pendingExtraction=null;
  const relevant=relevantQuestions(session.answers);session.currentQuestionId=preferred&&allowed.has(preferred)?preferred:relevant.find(q=>!isAnswered(session,q))?.id||null;
  const snapshot=state(session);session.progress=snapshot.progress;session.currentSection=snapshot.currentQuestion?.section||'Review';session.completedSections=snapshot.sections.filter(s=>s.total===s.completed).map(s=>s.name);session.status=snapshot.currentQuestion?'IN_PROGRESS':'REVIEW';return snapshot;
}
function questionFor(session,id){const q=relevantQuestions(session.answers).find(q=>q.id===id);if(!q)invalid('This question is not part of your current path.');return q;}
function validatedAnswer(question,value,options){const result=validate(question,value,options);if(question.platform){if(question.platform==='OTHER'){const entries=result.map(v=>normalizePractice('OTHER',v));if(new Set(entries.map(v=>v.platformLabel.toLowerCase())).size!==entries.length)invalid('Use one entry per custom platform.');return entries;}return normalizePractice(question.platform,result);}return result;}
function answer(session,id,value,raw){if(JSON.stringify(value??null).length>65536||JSON.stringify(raw??null).length>65536)invalid("Keep each answer under 64 KB; use concise descriptions and links.");const q=questionFor(session,id);const cleaned=validatedAnswer(q,value);if(cleaned===null)invalid('Enter an answer or skip this optional question.');session.answers={...session.answers,[id]:cleaned};session.rawAnswers={...session.rawAnswers,[id]:raw??value};session.history=[...(session.history||[]),{questionId:id,rawAnswer:raw??value,at:new Date()}].slice(-100);while(JSON.stringify(session.history).length>262144)session.history.shift();session.skippedQuestions=(session.skippedQuestions||[]).filter(v=>v!==id);session.pendingExtraction=null;return reconcile(session);}
function skip(session,id){const q=questionFor(session,id);if(q.required)invalid('This question is needed before publishing.');delete session.answers[id];session.skippedQuestions=[...new Set([...(session.skippedQuestions||[]),id])];session.pendingExtraction=null;return reconcile(session);}
function back(session){const relevant=relevantQuestions(session.answers);const index=relevant.findIndex(q=>q.id===session.currentQuestionId);const previous=relevant[Math.max(0,index<0?relevant.length-1:index-1)];session.currentQuestionId=previous?.id||null;session.currentSection=previous?.section||'Review';return state(session);}
module.exports={matches,relevantQuestions,state,reconcile,questionFor,validatedAnswer,answer,skip,back};
