const engine=require('./alumniQuestionEngine');
const {privacyFields,legacyFields}=require('./alumniStoryService');
const {invalid}=require('./alumniChatValidation');
function initialSession(user,profile,alumni){
 const prefill={name:user.name,...(profile?.collegeId?{college:{collegeId:profile.collegeId,name:profile.collegeName||profile.college}}:{}),...(profile?.branch?{branch:profile.branch}:{}),...(profile?.graduationYear?{graduationYear:profile.graduationYear}:{}),...(profile?.linkedinUrl?{socialLinks:{linkedin:profile.linkedinUrl}}:{})};
 const platforms=[];for(const [platform,key]of [['GITHUB','github'],['LEETCODE','leetcode']])if(profile?.[`${key}Url`]||profile?.[`${key}Username`]){platforms.push(platform);prefill[`practice:${platform}`]={profileUrl:profile[`${key}Url`]||(platform==='GITHUB'?`https://github.com/${profile.githubUsername}`:`https://leetcode.com/u/${profile.leetcodeUsername}/`),username:profile[`${key}Username`]||''};}if(platforms.length)prefill.platforms=platforms;
 if(profile?.avatarUrl||user.avatarUrl)prefill.introduction={avatarUrl:profile?.avatarUrl||user.avatarUrl};
 const session={userId:user._id,answers:{},rawAnswers:{},skippedQuestions:[],history:[],prefill:alumni?.onboardingVersion===1?alumni.story:prefill};engine.reconcile(session);return session;
}
function ownerSnapshot(session,extra={}){const value=session.toObject?session.toObject():session;return {session:{id:String(value._id||''),version:value.__v||0,status:value.status,answers:value.answers,rawAnswers:value.rawAnswers,extractedAnswers:value.extractedAnswers,pendingExtraction:value.pendingExtraction,skippedQuestions:value.skippedQuestions,prefill:value.prefill,lastActivityAt:value.lastActivityAt,publishedAlumniId:value.publishedAlumniId,...engine.state(value)},privacyFields:privacyFields(value.answers),...extra};}
function buildPublication(session,college){const info=engine.state(session);if(!info.canPublish)invalid('Complete the required answers and confirm any extraction before publishing.');const story={};for(const q of engine.relevantQuestions(session.answers))if(Object.hasOwn(session.answers,q.id))story[q.id]=engine.validatedAnswer(q,session.answers[q.id]);if(!college)invalid('Select a recognised college before publishing.');story.college={name:college.name,collegeId:college.collegeId};const legacy=legacyFields(story);return {...Object.fromEntries(Object.entries(legacy).map(([k,v])=>[k,v===undefined?null:v])),college:college.name,collegeName:college.name,collegeRef:college._id,collegeId:college.collegeId,story,onboardingVersion:1,privacy:story.privacy||{},publicationStatus:'PUBLISHED',publishedAt:new Date(),profileCompletion:info.progress,verified:false,verification:{identity:'UNVERIFIED',placement:'UNVERIFIED',gate:'UNVERIFIED',github:'UNVERIFIED',leetcode:'UNVERIFIED'},dataQuality:{completenessScore:info.progress,verifiedFields:0,estimatedFields:Object.values(session.extractedAnswers||{}).flatMap(v=>v.estimatedFields||[]),lastReviewedAt:new Date()}};}
module.exports={initialSession,ownerSnapshot,buildPublication};
