const { generateAI } = require("./ai/aiService");
const { buildJobDescriptionPrompt } = require("./ai/prompts");
const { normalizeSkillList } = require("./alumniMatchingService");

function parse(text) { const match = String(text || "").match(/\{[\s\S]*\}/); if (!match) return null; try { return JSON.parse(match[0]); } catch { return null; } }
function clean(value = {}) { return { requiredSkills: normalizeSkillList(value.requiredSkills), preferredSkills: normalizeSkillList(value.preferredSkills), csFundamentals: normalizeSkillList(value.csFundamentals), minimumCgpa: Number.isFinite(Number(value.minimumCgpa)) ? Number(value.minimumCgpa) : null, allowedBranches: Array.isArray(value.allowedBranches) ? value.allowedBranches.map(String).filter(Boolean).slice(0, 20) : [], graduationYears: Array.isArray(value.graduationYears) ? value.graduationYears.map(Number).filter(Number.isFinite).slice(0, 20) : [], experienceLevel: ["intern", "entry-level", "junior", "mid", "senior"].includes(value.experienceLevel) ? value.experienceLevel : "unspecified", responsibilities: Array.isArray(value.responsibilities) ? value.responsibilities.map(String).filter(Boolean).slice(0, 20) : [] }; }
function fallback(description) { const lower = String(description || "").toLowerCase(); const candidates = ["javascript", "typescript", "react", "node.js", "python", "java", "sql", "mongodb", "docker", "aws", "dbms", "operating systems", "computer networks", "dsa"]; return clean({ requiredSkills: candidates.filter((skill) => new RegExp(`\\b${skill.replace(".", "\\.")}\\b`, "i").test(lower)) }); }
async function analyzeJobDescription(input) { const safeFallback = fallback(input.description); if (!process.env.GEMINI_API_KEY) return { analysis: safeFallback, source: "deterministic" }; try { const text = await generateAI({ prompt: buildJobDescriptionPrompt(input), task: "job-jd-analysis", timeoutMs: 15000 }); return { analysis: clean(parse(text) || safeFallback), source: parse(text) ? "gemini" : "deterministic" }; } catch { return { analysis: safeFallback, source: "deterministic" }; } }
module.exports = { analyzeJobDescription };
