const { generateAI } = require("./ai/aiService");
const { buildJobDescriptionPrompt } = require("./ai/prompts");
const { buildRawJobPostPrompt } = require("./ai/prompts");
const { normalizeSkillList } = require("./alumniMatchingService");

function parse(text) { const match = String(text || "").match(/\{[\s\S]*\}/); if (!match) return null; try { return JSON.parse(match[0]); } catch { return null; } }
function clean(value = {}) { return { requiredSkills: normalizeSkillList(value.requiredSkills), preferredSkills: normalizeSkillList(value.preferredSkills), csFundamentals: normalizeSkillList(value.csFundamentals), minimumCgpa: Number.isFinite(Number(value.minimumCgpa)) ? Number(value.minimumCgpa) : null, allowedBranches: Array.isArray(value.allowedBranches) ? value.allowedBranches.map(String).filter(Boolean).slice(0, 20) : [], graduationYears: Array.isArray(value.graduationYears) ? value.graduationYears.map(Number).filter(Number.isFinite).slice(0, 20) : [], experienceLevel: ["intern", "entry-level", "junior", "mid", "senior"].includes(value.experienceLevel) ? value.experienceLevel : "unspecified", responsibilities: Array.isArray(value.responsibilities) ? value.responsibilities.map(String).filter(Boolean).slice(0, 20) : [] }; }
function fallback(description) { const lower = String(description || "").toLowerCase(); const candidates = ["javascript", "typescript", "react", "node.js", "python", "java", "sql", "mongodb", "docker", "aws", "dbms", "operating systems", "computer networks", "dsa"]; return clean({ requiredSkills: candidates.filter((skill) => new RegExp(`\\b${skill.replace(".", "\\.")}\\b`, "i").test(lower)) }); }
async function analyzeJobDescription(input) { const safeFallback = fallback(input.description); if (!process.env.GEMINI_API_KEY) return { analysis: safeFallback, source: "deterministic" }; try { const text = await generateAI({ prompt: buildJobDescriptionPrompt(input), task: "job-jd-analysis", timeoutMs: 15000 }); return { analysis: clean(parse(text) || safeFallback), source: parse(text) ? "gemini" : "deterministic" }; } catch { return { analysis: safeFallback, source: "deterministic" }; } }
function urls(text) { return [...String(text || "").matchAll(/https?:\/\/[^\s<>"']+/gi)].map((match) => match[0].replace(/[),.;]+$/, "")); }
function rawFallback(rawText) { const text = String(rawText || "").slice(0, 20000); const lines = text.split(/\r?\n/).map((line) => line.trim()).filter(Boolean); const allUrls = urls(text); const linkedIn = allUrls.find((url) => /linkedin\.com\/jobs\/view\//i.test(url)); const jobId = linkedIn?.match(/jobs\/view\/(\d+)/i)?.[1] || null; const canonicalLinkedIn = jobId ? `https://www.linkedin.com/jobs/view/${jobId}/` : linkedIn || null; const official = allUrls.find((url) => !/linkedin\.com/i.test(url) && /(apply|career|job|greenhouse|lever|ashby|workday)/i.test(url)) || null; const title = lines.find((line) => /\b(developer|engineer|designer|analyst|intern|manager)\b/i.test(line)) || null; const company = title ? lines[Math.max(0, lines.indexOf(title) - 1)] || null : null; const location = lines.find((line) => /india|remote|hybrid|on-site|onsite/i.test(line) && line.length < 100) || null; const employmentType = /full[ -]?time/i.test(text) ? "full-time" : /internship|intern\b/i.test(text) ? "internship" : null; const workMode = /on[ -]?site/i.test(text) ? "on-site" : /hybrid/i.test(text) ? "hybrid" : /remote/i.test(text) ? "remote" : null; const education = [...new Set((text.match(/\b(B\.?Tech|BCA|MCA|BE|B\.?Sc)\b/gi) || []).map((item) => item.replace(/\./g, "")))]; const skills = ["html", "css", "javascript", "typescript", "react", "node.js", "sql", "figma", "responsive design", "ui/ux design", "frontend frameworks"].filter((skill) => text.toLowerCase().includes(skill)); const phone = text.match(/(?:whatsapp|phone)\s*[:\-]?\s*(\+?\d[\d\s-]{7,})/i)?.[1]?.replace(/\D/g, "") || null; return { title, company, location: { city: location?.split(",")[0] || null, state: location?.split(",")[1]?.trim() || null, country: /india/i.test(location || "") ? "India" : null, raw: location }, workMode, employmentType, experienceLevel: null, education, requiredSkills: [], preferredSkills: [], generalSkills: skills, csFundamentals: [], responsibilities: [], summary: null, salary: null, deadline: null, postedText: text.match(/\b\d+\s+days?\s+ago\b/i)?.[0] || null, applicantText: text.match(/\b\d+\+?\s+applicants?\b/i)?.[0] || null, hiringActivity: /actively reviewing applicants/i.test(text) ? "Actively reviewing applicants" : null, officialApplyUrl: official, contact: { email: text.match(/[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}/)?.[0] || null, phone: null, whatsapp: phone }, source: { detectedProvider: linkedIn ? "linkedin" : official ? "company-careers" : /whatsapp/i.test(text) ? "whatsapp" : "unknown", linkedinJobId: jobId, linkedinJobUrl: canonicalLinkedIn, sourceUrl: canonicalLinkedIn || official || allUrls[0] || null } }; }
function normalizeExtractedJobData(value, fallbackValue) { const data = { ...fallbackValue, ...(value || {}) }; const rawLocation = String(data.location?.raw || data.location || ""); const pieces = rawLocation.split(/\s*[·|]\s*/); const geographic = pieces.shift()?.trim() || null; const metadata = pieces.join(" · "); const posted = data.postedText || metadata.match(/\b\d+\s+(?:minutes?|hours?|days?|weeks?|months?)\s+ago\b/i)?.[0] || null; const applicants = data.applicantText || metadata.match(/\b(?:over\s+)?\d+[+,]?\s+(?:people\s+clicked|applicants?)\b/i)?.[0] || null; const hiring = data.hiringActivity || metadata.match(/actively reviewing applicants|promoted by hirer/i)?.[0] || null; const parts = geographic?.split(",").map((part) => part.trim()).filter(Boolean) || []; return { ...data, location: { city: data.location?.city || parts[0] || null, state: data.location?.state || (parts.length > 2 ? parts[1] : null), country: data.location?.country || parts.find((part) => /^india$/i.test(part)) || null, raw: geographic }, postedText: posted, applicantText: applicants, hiringActivity: hiring, requiredSkills: normalizeSkillList(data.requiredSkills), preferredSkills: normalizeSkillList(data.preferredSkills), generalSkills: normalizeSkillList(data.generalSkills), csFundamentals: normalizeSkillList(data.csFundamentals), education: Array.isArray(data.education) ? data.education.map(String).filter(Boolean) : [], responsibilities: Array.isArray(data.responsibilities) ? data.responsibilities.map(String).filter(Boolean).slice(0, 20) : [], source: { ...fallbackValue.source, ...(data.source || {}) }, contact: { ...fallbackValue.contact, ...(data.contact || {}) } }; }
const cleanRaw = normalizeExtractedJobData;
async function analyzeRawJobPost(rawText) { const fallbackValue = rawFallback(rawText); if (!process.env.GEMINI_API_KEY) return { data: normalizeExtractedJobData(fallbackValue, fallbackValue), source: "deterministic" }; try { const text = await generateAI({ prompt: buildRawJobPostPrompt(String(rawText).slice(0, 20000)), task: "raw-job-extraction", timeoutMs: 20000 }); return { data: cleanRaw(parse(text), fallbackValue), source: parse(text) ? "gemini" : "deterministic" }; } catch { return { data: normalizeExtractedJobData(fallbackValue, fallbackValue), source: "deterministic" }; } }
module.exports = { analyzeJobDescription, analyzeRawJobPost, normalizeExtractedJobData };
