import { useState } from 'react';
import { Link } from 'react-router-dom';
import API from '../Services/api';
import { readStudyLocal, writeStudyLocal } from '../utils/studyTools';
export default function LessonPractice({lesson,authenticated,scope='guest'}) {
  const [filter,setFilter]=useState('all');
  const questions=(lesson.practice || []).filter(q=>filter==='all'||filter==='pyq'&&q.isPYQ||q.type===filter);
  return <div className="study-tool-body"><h2>Chapter practice</h2><p>Work through the question, then compare your answer with the solution.</p><div className="studio-filters">{[['all','All'],['pyq','Previous-year'],['short','Short answer'],['long','Long answer'],['numerical','Numerical']].map(([id,label])=><button key={id} aria-pressed={filter===id} onClick={()=>setFilter(id)}>{label}</button>)}</div>{questions.length?questions.map(q=><WrittenQuestion key={q.id} question={q} lessonId={lesson._id} authenticated={authenticated} scope={scope}/>):<p>No written questions in this view yet. Mentors can attach chapter questions and sourced previous-year questions.</p>}</div>;
}
function WrittenQuestion({question,lessonId,authenticated,scope}) {
  const key=`newbert-practice:${scope}:${lessonId}:${question.id}`;
  const [answer,setAnswer]=useState(()=>{const draft=readStudyLocal(key,'');return typeof draft==='string'?draft:'';}),[solution,setSolution]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(true);
  const submit=async e=>{e.preventDefault();setBusy(true);setError('');try {const {data}=await API.post(`/study/lessons/${lessonId}/practice/${question.id}`,{answer});setSolution(data.solution);}catch(e){setError(e.response?.data?.message || 'The solution could not be loaded. Your answer is still here.');}finally{setBusy(false);}};
  return <article className="study-doubt-card"><div className="study-row"><strong>{question.type==='short'?'Short answer':question.type==='long'?'Long answer':'Numerical'}</strong><span>{question.isPYQ?`${question.exam} · ${question.year}`:'Mentor practice'}{question.marks?` · ${question.marks} marks`:''}</span></div><p className="study-summary">{question.question}</p>{question.isPYQ&&<a href={question.sourceUrl} target="_blank" rel="noopener noreferrer">Original exam paper ↗</a>}{authenticated?<form onSubmit={submit} className="study-form"><label>Your answer / working<textarea disabled={busy} rows={5} maxLength={6000} required value={answer} onChange={e=>{setAnswer(e.target.value);setSolution('');const ok=writeStudyLocal(key,e.target.value);setSaved(ok);if(!ok)setError('This browser cannot save your draft. Keep this page open.');}} placeholder="Write the steps, formula or explanation here…"/></label><small>{saved?'Draft saved on this device.':'Draft is only available while this page is open.'}</small><button className="studio-primary" disabled={busy||!answer.trim()}>{busy?'Loading solution…':'Submit & compare'}</button>{error&&<p role="alert">{error}</p>}{solution&&<div className="study-mentor-reply"><strong>Model answer</strong><p className="study-summary">{solution}</p><small>Compare your reasoning. Written answers are self-reviewed.</small></div>}</form>:<p><Link to="/profile">Sign in</Link> to write your answer and see the solution.</p>}</article>;
}
