import { useState } from 'react';
export default function StudyConceptLab({code}) {
  const [service,setService] = useState('IaaS');
  const [coding,setCoding] = useState(5);
  const [documentation,setDocumentation] = useState(3);
  const [step,setStep] = useState(0);
  if(code==='BCS071'||code==='BOE082') return <section className="academic-lab"><p className="studio-eyebrow">TRY THE IDEA / CLOUD RESPONSIBILITY</p><h3>Who manages each layer?</h3><div className="studio-filters">{['IaaS','PaaS','SaaS'].map(s=><button key={s} aria-pressed={service===s} onClick={()=>setService(s)}>{s}</button>)}</div><div className="cloud-stack">{['Application','Runtime','Operating system','Virtualization','Hardware'].map((layer,i)=>{const yours=service==='IaaS'?i<3:service==='PaaS'?i<1:false;return <div key={layer} className={yours?'yours':'provider'}><span>{layer}</span><strong>{yours?'Your team':'Provider'}</strong></div>;})}</div><p>This simplified stack compares typical service boundaries. Your team still controls its data use and access choices; exact responsibilities depend on the service.</p></section>;
  if(code==='BOE070') return <section className="academic-lab"><p className="studio-eyebrow">TRY THE IDEA / CRITICAL PATH</p><h3>Can you shorten the project?</h3><label>Coding · {coding} days<input aria-label="Coding duration" type="range" min="1" max="10" value={coding} onChange={e=>setCoding(Number(e.target.value))}/></label><label>Documentation · {documentation} days<input aria-label="Documentation duration" type="range" min="1" max="10" value={documentation} onChange={e=>setDocumentation(Number(e.target.value))}/></label><div className="project-network"><span>Design<br/><b>2 days</b></span><span className="project-parallel"><i className={coding>=documentation?'critical':''}>Code · {coding}d</i><i className={documentation>=coding?'critical':''}>Docs · {documentation}d</i></span><span>Test<br/><b>2 days</b></span></div><p role="status"><strong>Earliest finish: {4+Math.max(coding,documentation)} days.</strong> {coding===documentation?'Both parallel paths are critical.':`${coding>documentation?'Coding':'Documentation'} controls the parallel stage.`}</p><small>Design → parallel coding/docs → testing. Assumes independent resources and fixed dependencies.</small></section>;
  if(code==='BCS701') {const path=['S','A','B','C','D','G'];return <section className="academic-lab"><p className="studio-eyebrow">TRY THE IDEA / BREADTH-FIRST SEARCH</p><h3>Explore one level at a time.</h3><div className="search-tree">{[['S'],['A','B'],['C','D','G']].map((row,i)=><div key={i}>{row.map(n=><span key={n} className={path.indexOf(n)<=step?'visited':''}>{n}</span>)}</div>)}</div><p>Edges: S → A,B; A → C,D; B → G. Equal edge costs; neighbors enter the queue left to right.</p><p role="status"><strong>Expanded: {path.slice(0,step+1).join(' → ')}</strong>{step===5?' · Goal reached through S → B → G.':''}</p><div className="studio-hero-links"><button className="studio-primary" disabled={step===5} onClick={()=>setStep(s=>s+1)}>Expand next node</button><button className="studio-secondary" onClick={()=>setStep(0)}>Reset</button></div></section>;}
  return null;
}
